{"id":545885252,"status":"canceled","stage":"stage-4","name":"library:ci-corn","ref":"pr-12294","tag":false,"coverage":null,"allow_failure":false,"created_at":"2020-05-10T18:46:51.115Z","started_at":"2020-05-10T19:15:51.900Z","finished_at":"2020-05-10T19:28:54.018Z","duration":782.11754,"queued_duration":1.224015,"user":{"id":2256237,"username":"coqbot","name":"coqbot","state":"active","avatar_url":"https://gitlab.com/uploads/-/system/user/avatar/2256237/avatar.png","web_url":"https://gitlab.com/coqbot","created_at":"2018-04-28T07:53:57.210Z","bio":"Hello, I'm a bot.","location":"","public_email":"","skype":"","linkedin":"","twitter":"","website_url":"","organization":"","job_title":"","pronouns":null,"bot":false,"work_information":null,"followers":0,"following":0,"local_time":null},"commit":{"id":"9bd08e99256614045cc9ef1f32a6a7b4fec56d50","short_id":"9bd08e99","created_at":"2020-05-10T20:42:16.000+02:00","parent_ids":["f40839ee880ac3e79d560e26f55f462f8ffd2e05"],"title":"[errors] Don't raise inside exception printers","message":"[errors] Don't raise inside exception printers\n\nThis is wrong and not properly handled anymore, instead the handlers\nare expected to return the error message.\n\nThis is a partial backport of #11498 , as it turns out this doesn't\nmake sense in 8.11 neither.\n\nFixes #12291\n","author_name":"Emilio Jesus Gallego Arias","author_email":"e+git@x80.org","authored_date":"2020-05-10T20:42:16.000+02:00","committer_name":"Emilio Jesus Gallego Arias","committer_email":"e+git@x80.org","committed_date":"2020-05-10T20:42:16.000+02:00","trailers":{},"web_url":"https://gitlab.com/coq/coq/-/commit/9bd08e99256614045cc9ef1f32a6a7b4fec56d50"},"pipeline":{"id":144552572,"iid":15987,"project_id":6138686,"sha":"9bd08e99256614045cc9ef1f32a6a7b4fec56d50","ref":"pr-12294","status":"failed","source":"push","created_at":"2020-05-10T18:46:50.220Z","updated_at":"2020-05-10T19:28:54.279Z","web_url":"https://gitlab.com/coq/coq/-/pipelines/144552572"},"web_url":"https://gitlab.com/coq/coq/-/jobs/545885252","artifacts":[{"file_type":"trace","size":192268,"filename":"job.log","file_format":null}],"runner":{"id":380987,"description":"shared-runners-manager-6.gitlab.com","ip_address":"34.74.239.13","active":true,"paused":false,"is_shared":true,"runner_type":"instance_type","name":"gitlab-runner","online":false,"status":"stale"},"artifacts_expire_at":null,"tag_list":[]}
{"id":545885251,"status":"success","stage":"stage-3","name":"library:ci-math-classes","ref":"pr-12294","tag":false,"coverage":null,"allow_failure":false,"created_at":"2020-05-10T18:46:51.099Z","started_at":"2020-05-10T19:09:43.379Z","finished_at":"2020-05-10T19:15:50.546Z","duration":367.166762,"queued_duration":0.845292,"user":{"id":2256237,"username":"coqbot","name":"coqbot","state":"active","avatar_url":"https://gitlab.com/uploads/-/system/user/avatar/2256237/avatar.png","web_url":"https://gitlab.com/coqbot","created_at":"2018-04-28T07:53:57.210Z","bio":"Hello, I'm a bot.","location":"","public_email":"","skype":"","linkedin":"","twitter":"","website_url":"","organization":"","job_title":"","pronouns":null,"bot":false,"work_information":null,"followers":0,"following":0,"local_time":null},"commit":{"id":"9bd08e99256614045cc9ef1f32a6a7b4fec56d50","short_id":"9bd08e99","created_at":"2020-05-10T20:42:16.000+02:00","parent_ids":["f40839ee880ac3e79d560e26f55f462f8ffd2e05"],"title":"[errors] Don't raise inside exception printers","message":"[errors] Don't raise inside exception printers\n\nThis is wrong and not properly handled anymore, instead the handlers\nare expected to return the error message.\n\nThis is a partial backport of #11498 , as it turns out this doesn't\nmake sense in 8.11 neither.\n\nFixes #12291\n","author_name":"Emilio Jesus Gallego Arias","author_email":"e+git@x80.org","authored_date":"2020-05-10T20:42:16.000+02:00","committer_name":"Emilio Jesus Gallego Arias","committer_email":"e+git@x80.org","committed_date":"2020-05-10T20:42:16.000+02:00","trailers":{},"web_url":"https://gitlab.com/coq/coq/-/commit/9bd08e99256614045cc9ef1f32a6a7b4fec56d50"},"pipeline":{"id":144552572,"iid":15987,"project_id":6138686,"sha":"9bd08e99256614045cc9ef1f32a6a7b4fec56d50","ref":"pr-12294","status":"failed","source":"push","created_at":"2020-05-10T18:46:50.220Z","updated_at":"2020-05-10T19:28:54.279Z","web_url":"https://gitlab.com/coq/coq/-/pipelines/144552572"},"web_url":"https://gitlab.com/coq/coq/-/jobs/545885251","artifacts":[{"file_type":"trace","size":201488,"filename":"job.log","file_format":null}],"runner":null,"artifacts_expire_at":null,"tag_list":[]}
{"id":545885250,"status":"success","stage":"stage-3","name":"library:ci-color","ref":"pr-12294","tag":false,"coverage":null,"allow_failure":false,"created_at":"2020-05-10T18:46:51.083Z","started_at":"2020-05-10T19:09:42.994Z","finished_at":"2020-05-10T19:25:53.219Z","duration":970.224902,"queued_duration":0.517339,"user":{"id":2256237,"username":"coqbot","name":"coqbot","state":"active","avatar_url":"https://gitlab.com/uploads/-/system/user/avatar/2256237/avatar.png","web_url":"https://gitlab.com/coqbot","created_at":"2018-04-28T07:53:57.210Z","bio":"Hello, I'm a bot.","location":"","public_email":"","skype":"","linkedin":"","twitter":"","website_url":"","organization":"","job_title":"","pronouns":null,"bot":false,"work_information":null,"followers":0,"following":0,"local_time":null},"commit":{"id":"9bd08e99256614045cc9ef1f32a6a7b4fec56d50","short_id":"9bd08e99","created_at":"2020-05-10T20:42:16.000+02:00","parent_ids":["f40839ee880ac3e79d560e26f55f462f8ffd2e05"],"title":"[errors] Don't raise inside exception printers","message":"[errors] Don't raise inside exception printers\n\nThis is wrong and not properly handled anymore, instead the handlers\nare expected to return the error message.\n\nThis is a partial backport of #11498 , as it turns out this doesn't\nmake sense in 8.11 neither.\n\nFixes #12291\n","author_name":"Emilio Jesus Gallego Arias","author_email":"e+git@x80.org","authored_date":"2020-05-10T20:42:16.000+02:00","committer_name":"Emilio Jesus Gallego Arias","committer_email":"e+git@x80.org","committed_date":"2020-05-10T20:42:16.000+02:00","trailers":{},"web_url":"https://gitlab.com/coq/coq/-/commit/9bd08e99256614045cc9ef1f32a6a7b4fec56d50"},"pipeline":{"id":144552572,"iid":15987,"project_id":6138686,"sha":"9bd08e99256614045cc9ef1f32a6a7b4fec56d50","ref":"pr-12294","status":"failed","source":"push","created_at":"2020-05-10T18:46:50.220Z","updated_at":"2020-05-10T19:28:54.279Z","web_url":"https://gitlab.com/coq/coq/-/pipelines/144552572"},"web_url":"https://gitlab.com/coq/coq/-/jobs/545885250","artifacts":[{"file_type":"trace","size":237561,"filename":"job.log","file_format":null}],"runner":null,"artifacts_expire_at":null,"tag_list":[]}
{"id":545885249,"status":"success","stage":"stage-2","name":"plugin:ci-relation_algebra","ref":"pr-12294","tag":false,"coverage":null,"allow_failure":false,"created_at":"2020-05-10T18:46:51.069Z","started_at":"2020-05-10T18:56:19.498Z","finished_at":"2020-05-10T19:02:14.340Z","duration":354.841418,"queued_duration":2.093033,"user":{"id":2256237,"username":"coqbot","name":"coqbot","state":"active","avatar_url":"https://gitlab.com/uploads/-/system/user/avatar/2256237/avatar.png","web_url":"https://gitlab.com/coqbot","created_at":"2018-04-28T07:53:57.210Z","bio":"Hello, I'm a bot.","location":"","public_email":"","skype":"","linkedin":"","twitter":"","website_url":"","organization":"","job_title":"","pronouns":null,"bot":false,"work_information":null,"followers":0,"following":0,"local_time":null},"commit":{"id":"9bd08e99256614045cc9ef1f32a6a7b4fec56d50","short_id":"9bd08e99","created_at":"2020-05-10T20:42:16.000+02:00","parent_ids":["f40839ee880ac3e79d560e26f55f462f8ffd2e05"],"title":"[errors] Don't raise inside exception printers","message":"[errors] Don't raise inside exception printers\n\nThis is wrong and not properly handled anymore, instead the handlers\nare expected to return the error message.\n\nThis is a partial backport of #11498 , as it turns out this doesn't\nmake sense in 8.11 neither.\n\nFixes #12291\n","author_name":"Emilio Jesus Gallego Arias","author_email":"e+git@x80.org","authored_date":"2020-05-10T20:42:16.000+02:00","committer_name":"Emilio Jesus Gallego Arias","committer_email":"e+git@x80.org","committed_date":"2020-05-10T20:42:16.000+02:00","trailers":{},"web_url":"https://gitlab.com/coq/coq/-/commit/9bd08e99256614045cc9ef1f32a6a7b4fec56d50"},"pipeline":{"id":144552572,"iid":15987,"project_id":6138686,"sha":"9bd08e99256614045cc9ef1f32a6a7b4fec56d50","ref":"pr-12294","status":"failed","source":"push","created_at":"2020-05-10T18:46:50.220Z","updated_at":"2020-05-10T19:28:54.279Z","web_url":"https://gitlab.com/coq/coq/-/pipelines/144552572"},"web_url":"https://gitlab.com/coq/coq/-/jobs/545885249","artifacts":[{"file_type":"trace","size":56491,"filename":"job.log","file_format":null}],"runner":{"id":380987,"description":"shared-runners-manager-6.gitlab.com","ip_address":"34.74.239.13","active":true,"paused":false,"is_shared":true,"runner_type":"instance_type","name":"gitlab-runner","online":false,"status":"stale"},"artifacts_expire_at":null,"tag_list":[]}
{"id":545885248,"status":"success","stage":"stage-2","name":"plugin:ci-quickchick","ref":"pr-12294","tag":false,"coverage":null,"allow_failure":false,"created_at":"2020-05-10T18:46:51.053Z","started_at":"2020-05-10T19:06:41.159Z","finished_at":"2020-05-10T19:12:59.580Z","duration":378.420319,"queued_duration":61.44497,"user":{"id":2256237,"username":"coqbot","name":"coqbot","state":"active","avatar_url":"https://gitlab.com/uploads/-/system/user/avatar/2256237/avatar.png","web_url":"https://gitlab.com/coqbot","created_at":"2018-04-28T07:53:57.210Z","bio":"Hello, I'm a bot.","location":"","public_email":"","skype":"","linkedin":"","twitter":"","website_url":"","organization":"","job_title":"","pronouns":null,"bot":false,"work_information":null,"followers":0,"following":0,"local_time":null},"commit":{"id":"9bd08e99256614045cc9ef1f32a6a7b4fec56d50","short_id":"9bd08e99","created_at":"2020-05-10T20:42:16.000+02:00","parent_ids":["f40839ee880ac3e79d560e26f55f462f8ffd2e05"],"title":"[errors] Don't raise inside exception printers","message":"[errors] Don't raise inside exception printers\n\nThis is wrong and not properly handled anymore, instead the handlers\nare expected to return the error message.\n\nThis is a partial backport of #11498 , as it turns out this doesn't\nmake sense in 8.11 neither.\n\nFixes #12291\n","author_name":"Emilio Jesus Gallego Arias","author_email":"e+git@x80.org","authored_date":"2020-05-10T20:42:16.000+02:00","committer_name":"Emilio Jesus Gallego Arias","committer_email":"e+git@x80.org","committed_date":"2020-05-10T20:42:16.000+02:00","trailers":{},"web_url":"https://gitlab.com/coq/coq/-/commit/9bd08e99256614045cc9ef1f32a6a7b4fec56d50"},"pipeline":{"id":144552572,"iid":15987,"project_id":6138686,"sha":"9bd08e99256614045cc9ef1f32a6a7b4fec56d50","ref":"pr-12294","status":"failed","source":"push","created_at":"2020-05-10T18:46:50.220Z","updated_at":"2020-05-10T19:28:54.279Z","web_url":"https://gitlab.com/coq/coq/-/pipelines/144552572"},"web_url":"https://gitlab.com/coq/coq/-/jobs/545885248","artifacts":[{"file_type":"trace","size":230406,"filename":"job.log","file_format":null}],"runner":{"id":380987,"description":"shared-runners-manager-6.gitlab.com","ip_address":"34.74.239.13","active":true,"paused":false,"is_shared":true,"runner_type":"instance_type","name":"gitlab-runner","online":false,"status":"stale"},"artifacts_expire_at":null,"tag_list":[]}
{"id":545885247,"status":"canceled","stage":"stage-2","name":"plugin:ci-perennial","ref":"pr-12294","tag":false,"coverage":null,"allow_failure":false,"created_at":"2020-05-10T18:46:51.035Z","started_at":"2020-05-10T19:06:41.098Z","finished_at":"2020-05-10T19:28:54.008Z","duration":1332.909402,"queued_duration":61.434812,"user":{"id":2256237,"username":"coqbot","name":"coqbot","state":"active","avatar_url":"https://gitlab.com/uploads/-/system/user/avatar/2256237/avatar.png","web_url":"https://gitlab.com/coqbot","created_at":"2018-04-28T07:53:57.210Z","bio":"Hello, I'm a bot.","location":"","public_email":"","skype":"","linkedin":"","twitter":"","website_url":"","organization":"","job_title":"","pronouns":null,"bot":false,"work_information":null,"followers":0,"following":0,"local_time":null},"commit":{"id":"9bd08e99256614045cc9ef1f32a6a7b4fec56d50","short_id":"9bd08e99","created_at":"2020-05-10T20:42:16.000+02:00","parent_ids":["f40839ee880ac3e79d560e26f55f462f8ffd2e05"],"title":"[errors] Don't raise inside exception printers","message":"[errors] Don't raise inside exception printers\n\nThis is wrong and not properly handled anymore, instead the handlers\nare expected to return the error message.\n\nThis is a partial backport of #11498 , as it turns out this doesn't\nmake sense in 8.11 neither.\n\nFixes #12291\n","author_name":"Emilio Jesus Gallego Arias","author_email":"e+git@x80.org","authored_date":"2020-05-10T20:42:16.000+02:00","committer_name":"Emilio Jesus Gallego Arias","committer_email":"e+git@x80.org","committed_date":"2020-05-10T20:42:16.000+02:00","trailers":{},"web_url":"https://gitlab.com/coq/coq/-/commit/9bd08e99256614045cc9ef1f32a6a7b4fec56d50"},"pipeline":{"id":144552572,"iid":15987,"project_id":6138686,"sha":"9bd08e99256614045cc9ef1f32a6a7b4fec56d50","ref":"pr-12294","status":"failed","source":"push","created_at":"2020-05-10T18:46:50.220Z","updated_at":"2020-05-10T19:28:54.279Z","web_url":"https://gitlab.com/coq/coq/-/pipelines/144552572"},"web_url":"https://gitlab.com/coq/coq/-/jobs/545885247","artifacts":[{"file_type":"trace","size":37874,"filename":"job.log","file_format":null}],"runner":{"id":44949,"description":"shared-runners-manager-4.gitlab.com","ip_address":"13.37.237.197","active":true,"paused":false,"is_shared":true,"runner_type":"instance_type","name":"gitlab-runner","online":false,"status":"stale"},"artifacts_expire_at":null,"tag_list":[]}
{"id":545885246,"status":"success","stage":"stage-2","name":"plugin:ci-paramcoq","ref":"pr-12294","tag":false,"coverage":null,"allow_failure":false,"created_at":"2020-05-10T18:46:51.020Z","started_at":"2020-05-10T18:56:19.461Z","finished_at":"2020-05-10T18:59:26.884Z","duration":187.423011,"queued_duration":2.108035,"user":{"id":2256237,"username":"coqbot","name":"coqbot","state":"active","avatar_url":"https://gitlab.com/uploads/-/system/user/avatar/2256237/avatar.png","web_url":"https://gitlab.com/coqbot","created_at":"2018-04-28T07:53:57.210Z","bio":"Hello, I'm a bot.","location":"","public_email":"","skype":"","linkedin":"","twitter":"","website_url":"","organization":"","job_title":"","pronouns":null,"bot":false,"work_information":null,"followers":0,"following":0,"local_time":null},"commit":{"id":"9bd08e99256614045cc9ef1f32a6a7b4fec56d50","short_id":"9bd08e99","created_at":"2020-05-10T20:42:16.000+02:00","parent_ids":["f40839ee880ac3e79d560e26f55f462f8ffd2e05"],"title":"[errors] Don't raise inside exception printers","message":"[errors] Don't raise inside exception printers\n\nThis is wrong and not properly handled anymore, instead the handlers\nare expected to return the error message.\n\nThis is a partial backport of #11498 , as it turns out this doesn't\nmake sense in 8.11 neither.\n\nFixes #12291\n","author_name":"Emilio Jesus Gallego Arias","author_email":"e+git@x80.org","authored_date":"2020-05-10T20:42:16.000+02:00","committer_name":"Emilio Jesus Gallego Arias","committer_email":"e+git@x80.org","committed_date":"2020-05-10T20:42:16.000+02:00","trailers":{},"web_url":"https://gitlab.com/coq/coq/-/commit/9bd08e99256614045cc9ef1f32a6a7b4fec56d50"},"pipeline":{"id":144552572,"iid":15987,"project_id":6138686,"sha":"9bd08e99256614045cc9ef1f32a6a7b4fec56d50","ref":"pr-12294","status":"failed","source":"push","created_at":"2020-05-10T18:46:50.220Z","updated_at":"2020-05-10T19:28:54.279Z","web_url":"https://gitlab.com/coq/coq/-/pipelines/144552572"},"web_url":"https://gitlab.com/coq/coq/-/jobs/545885246","artifacts":[{"file_type":"trace","size":84888,"filename":"job.log","file_format":null}],"runner":{"id":44949,"description":"shared-runners-manager-4.gitlab.com","ip_address":"13.37.237.197","active":true,"paused":false,"is_shared":true,"runner_type":"instance_type","name":"gitlab-runner","online":false,"status":"stale"},"artifacts_expire_at":null,"tag_list":[]}
{"id":545885245,"status":"success","stage":"stage-2","name":"plugin:ci-mtac2","ref":"pr-12294","tag":false,"coverage":null,"allow_failure":false,"created_at":"2020-05-10T18:46:51.004Z","started_at":"2020-05-10T18:56:19.428Z","finished_at":"2020-05-10T19:00:46.431Z","duration":267.00283,"queued_duration":2.128575,"user":{"id":2256237,"username":"coqbot","name":"coqbot","state":"active","avatar_url":"https://gitlab.com/uploads/-/system/user/avatar/2256237/avatar.png","web_url":"https://gitlab.com/coqbot","created_at":"2018-04-28T07:53:57.210Z","bio":"Hello, I'm a bot.","location":"","public_email":"","skype":"","linkedin":"","twitter":"","website_url":"","organization":"","job_title":"","pronouns":null,"bot":false,"work_information":null,"followers":0,"following":0,"local_time":null},"commit":{"id":"9bd08e99256614045cc9ef1f32a6a7b4fec56d50","short_id":"9bd08e99","created_at":"2020-05-10T20:42:16.000+02:00","parent_ids":["f40839ee880ac3e79d560e26f55f462f8ffd2e05"],"title":"[errors] Don't raise inside exception printers","message":"[errors] Don't raise inside exception printers\n\nThis is wrong and not properly handled anymore, instead the handlers\nare expected to return the error message.\n\nThis is a partial backport of #11498 , as it turns out this doesn't\nmake sense in 8.11 neither.\n\nFixes #12291\n","author_name":"Emilio Jesus Gallego Arias","author_email":"e+git@x80.org","authored_date":"2020-05-10T20:42:16.000+02:00","committer_name":"Emilio Jesus Gallego Arias","committer_email":"e+git@x80.org","committed_date":"2020-05-10T20:42:16.000+02:00","trailers":{},"web_url":"https://gitlab.com/coq/coq/-/commit/9bd08e99256614045cc9ef1f32a6a7b4fec56d50"},"pipeline":{"id":144552572,"iid":15987,"project_id":6138686,"sha":"9bd08e99256614045cc9ef1f32a6a7b4fec56d50","ref":"pr-12294","status":"failed","source":"push","created_at":"2020-05-10T18:46:50.220Z","updated_at":"2020-05-10T19:28:54.279Z","web_url":"https://gitlab.com/coq/coq/-/pipelines/144552572"},"web_url":"https://gitlab.com/coq/coq/-/jobs/545885245","artifacts":[{"file_type":"trace","size":144424,"filename":"job.log","file_format":null}],"runner":{"id":380987,"description":"shared-runners-manager-6.gitlab.com","ip_address":"34.74.239.13","active":true,"paused":false,"is_shared":true,"runner_type":"instance_type","name":"gitlab-runner","online":false,"status":"stale"},"artifacts_expire_at":null,"tag_list":[]}
{"id":545885244,"status":"success","stage":"stage-2","name":"plugin:ci-fiat_parsers","ref":"pr-12294","tag":false,"coverage":null,"allow_failure":false,"created_at":"2020-05-10T18:46:50.985Z","started_at":"2020-05-10T18:56:19.344Z","finished_at":"2020-05-10T19:14:14.170Z","duration":1074.825596,"queued_duration":2.095761,"user":{"id":2256237,"username":"coqbot","name":"coqbot","state":"active","avatar_url":"https://gitlab.com/uploads/-/system/user/avatar/2256237/avatar.png","web_url":"https://gitlab.com/coqbot","created_at":"2018-04-28T07:53:57.210Z","bio":"Hello, I'm a bot.","location":"","public_email":"","skype":"","linkedin":"","twitter":"","website_url":"","organization":"","job_title":"","pronouns":null,"bot":false,"work_information":null,"followers":0,"following":0,"local_time":null},"commit":{"id":"9bd08e99256614045cc9ef1f32a6a7b4fec56d50","short_id":"9bd08e99","created_at":"2020-05-10T20:42:16.000+02:00","parent_ids":["f40839ee880ac3e79d560e26f55f462f8ffd2e05"],"title":"[errors] Don't raise inside exception printers","message":"[errors] Don't raise inside exception printers\n\nThis is wrong and not properly handled anymore, instead the handlers\nare expected to return the error message.\n\nThis is a partial backport of #11498 , as it turns out this doesn't\nmake sense in 8.11 neither.\n\nFixes #12291\n","author_name":"Emilio Jesus Gallego Arias","author_email":"e+git@x80.org","authored_date":"2020-05-10T20:42:16.000+02:00","committer_name":"Emilio Jesus Gallego Arias","committer_email":"e+git@x80.org","committed_date":"2020-05-10T20:42:16.000+02:00","trailers":{},"web_url":"https://gitlab.com/coq/coq/-/commit/9bd08e99256614045cc9ef1f32a6a7b4fec56d50"},"pipeline":{"id":144552572,"iid":15987,"project_id":6138686,"sha":"9bd08e99256614045cc9ef1f32a6a7b4fec56d50","ref":"pr-12294","status":"failed","source":"push","created_at":"2020-05-10T18:46:50.220Z","updated_at":"2020-05-10T19:28:54.279Z","web_url":"https://gitlab.com/coq/coq/-/pipelines/144552572"},"web_url":"https://gitlab.com/coq/coq/-/jobs/545885244","artifacts":[{"file_type":"trace","size":294358,"filename":"job.log","file_format":null}],"runner":null,"artifacts_expire_at":null,"tag_list":[]}
{"id":545885242,"status":"success","stage":"stage-2","name":"plugin:ci-equations","ref":"pr-12294","tag":false,"coverage":null,"allow_failure":false,"created_at":"2020-05-10T18:46:50.970Z","started_at":"2020-05-10T18:56:19.290Z","finished_at":"2020-05-10T19:05:02.053Z","duration":522.762914,"queued_duration":2.092385,"user":{"id":2256237,"username":"coqbot","name":"coqbot","state":"active","avatar_url":"https://gitlab.com/uploads/-/system/user/avatar/2256237/avatar.png","web_url":"https://gitlab.com/coqbot","created_at":"2018-04-28T07:53:57.210Z","bio":"Hello, I'm a bot.","location":"","public_email":"","skype":"","linkedin":"","twitter":"","website_url":"","organization":"","job_title":"","pronouns":null,"bot":false,"work_information":null,"followers":0,"following":0,"local_time":null},"commit":{"id":"9bd08e99256614045cc9ef1f32a6a7b4fec56d50","short_id":"9bd08e99","created_at":"2020-05-10T20:42:16.000+02:00","parent_ids":["f40839ee880ac3e79d560e26f55f462f8ffd2e05"],"title":"[errors] Don't raise inside exception printers","message":"[errors] Don't raise inside exception printers\n\nThis is wrong and not properly handled anymore, instead the handlers\nare expected to return the error message.\n\nThis is a partial backport of #11498 , as it turns out this doesn't\nmake sense in 8.11 neither.\n\nFixes #12291\n","author_name":"Emilio Jesus Gallego Arias","author_email":"e+git@x80.org","authored_date":"2020-05-10T20:42:16.000+02:00","committer_name":"Emilio Jesus Gallego Arias","committer_email":"e+git@x80.org","committed_date":"2020-05-10T20:42:16.000+02:00","trailers":{},"web_url":"https://gitlab.com/coq/coq/-/commit/9bd08e99256614045cc9ef1f32a6a7b4fec56d50"},"pipeline":{"id":144552572,"iid":15987,"project_id":6138686,"sha":"9bd08e99256614045cc9ef1f32a6a7b4fec56d50","ref":"pr-12294","status":"failed","source":"push","created_at":"2020-05-10T18:46:50.220Z","updated_at":"2020-05-10T19:28:54.279Z","web_url":"https://gitlab.com/coq/coq/-/pipelines/144552572"},"web_url":"https://gitlab.com/coq/coq/-/jobs/545885242","artifacts":[{"file_type":"trace","size":102443,"filename":"job.log","file_format":null}],"runner":{"id":380986,"description":"shared-runners-manager-5.gitlab.com","ip_address":"34.74.209.140","active":true,"paused":false,"is_shared":true,"runner_type":"instance_type","name":"gitlab-runner","online":false,"status":"stale"},"artifacts_expire_at":null,"tag_list":[]}
{"id":545885241,"status":"success","stage":"stage-2","name":"plugin:ci-elpi","ref":"pr-12294","tag":false,"coverage":null,"allow_failure":false,"created_at":"2020-05-10T18:46:50.956Z","started_at":"2020-05-10T18:56:19.250Z","finished_at":"2020-05-10T19:00:16.838Z","duration":237.587393,"queued_duration":2.098882,"user":{"id":2256237,"username":"coqbot","name":"coqbot","state":"active","avatar_url":"https://gitlab.com/uploads/-/system/user/avatar/2256237/avatar.png","web_url":"https://gitlab.com/coqbot","created_at":"2018-04-28T07:53:57.210Z","bio":"Hello, I'm a bot.","location":"","public_email":"","skype":"","linkedin":"","twitter":"","website_url":"","organization":"","job_title":"","pronouns":null,"bot":false,"work_information":null,"followers":0,"following":0,"local_time":null},"commit":{"id":"9bd08e99256614045cc9ef1f32a6a7b4fec56d50","short_id":"9bd08e99","created_at":"2020-05-10T20:42:16.000+02:00","parent_ids":["f40839ee880ac3e79d560e26f55f462f8ffd2e05"],"title":"[errors] Don't raise inside exception printers","message":"[errors] Don't raise inside exception printers\n\nThis is wrong and not properly handled anymore, instead the handlers\nare expected to return the error message.\n\nThis is a partial backport of #11498 , as it turns out this doesn't\nmake sense in 8.11 neither.\n\nFixes #12291\n","author_name":"Emilio Jesus Gallego Arias","author_email":"e+git@x80.org","authored_date":"2020-05-10T20:42:16.000+02:00","committer_name":"Emilio Jesus Gallego Arias","committer_email":"e+git@x80.org","committed_date":"2020-05-10T20:42:16.000+02:00","trailers":{},"web_url":"https://gitlab.com/coq/coq/-/commit/9bd08e99256614045cc9ef1f32a6a7b4fec56d50"},"pipeline":{"id":144552572,"iid":15987,"project_id":6138686,"sha":"9bd08e99256614045cc9ef1f32a6a7b4fec56d50","ref":"pr-12294","status":"failed","source":"push","created_at":"2020-05-10T18:46:50.220Z","updated_at":"2020-05-10T19:28:54.279Z","web_url":"https://gitlab.com/coq/coq/-/pipelines/144552572"},"web_url":"https://gitlab.com/coq/coq/-/jobs/545885241","artifacts":[{"file_type":"trace","size":378586,"filename":"job.log","file_format":null}],"runner":{"id":44028,"description":"shared-runners-manager-3.gitlab.com","ip_address":"35.196.21.178","active":true,"paused":false,"is_shared":true,"runner_type":"instance_type","name":"gitlab-runner","online":false,"status":"stale"},"artifacts_expire_at":null,"tag_list":[]}
{"id":545885240,"status":"success","stage":"stage-2","name":"plugin:ci-coqhammer","ref":"pr-12294","tag":false,"coverage":null,"allow_failure":false,"created_at":"2020-05-10T18:46:50.944Z","started_at":"2020-05-10T18:56:18.985Z","finished_at":"2020-05-10T18:58:36.144Z","duration":137.159478,"queued_duration":1.883247,"user":{"id":2256237,"username":"coqbot","name":"coqbot","state":"active","avatar_url":"https://gitlab.com/uploads/-/system/user/avatar/2256237/avatar.png","web_url":"https://gitlab.com/coqbot","created_at":"2018-04-28T07:53:57.210Z","bio":"Hello, I'm a bot.","location":"","public_email":"","skype":"","linkedin":"","twitter":"","website_url":"","organization":"","job_title":"","pronouns":null,"bot":false,"work_information":null,"followers":0,"following":0,"local_time":null},"commit":{"id":"9bd08e99256614045cc9ef1f32a6a7b4fec56d50","short_id":"9bd08e99","created_at":"2020-05-10T20:42:16.000+02:00","parent_ids":["f40839ee880ac3e79d560e26f55f462f8ffd2e05"],"title":"[errors] Don't raise inside exception printers","message":"[errors] Don't raise inside exception printers\n\nThis is wrong and not properly handled anymore, instead the handlers\nare expected to return the error message.\n\nThis is a partial backport of #11498 , as it turns out this doesn't\nmake sense in 8.11 neither.\n\nFixes #12291\n","author_name":"Emilio Jesus Gallego Arias","author_email":"e+git@x80.org","authored_date":"2020-05-10T20:42:16.000+02:00","committer_name":"Emilio Jesus Gallego Arias","committer_email":"e+git@x80.org","committed_date":"2020-05-10T20:42:16.000+02:00","trailers":{},"web_url":"https://gitlab.com/coq/coq/-/commit/9bd08e99256614045cc9ef1f32a6a7b4fec56d50"},"pipeline":{"id":144552572,"iid":15987,"project_id":6138686,"sha":"9bd08e99256614045cc9ef1f32a6a7b4fec56d50","ref":"pr-12294","status":"failed","source":"push","created_at":"2020-05-10T18:46:50.220Z","updated_at":"2020-05-10T19:28:54.279Z","web_url":"https://gitlab.com/coq/coq/-/pipelines/144552572"},"web_url":"https://gitlab.com/coq/coq/-/jobs/545885240","artifacts":[{"file_type":"trace","size":70270,"filename":"job.log","file_format":null}],"runner":null,"artifacts_expire_at":null,"tag_list":[]}
{"id":545885239,"status":"success","stage":"stage-2","name":"plugin:ci-coq_dpdgraph","ref":"pr-12294","tag":false,"coverage":null,"allow_failure":false,"created_at":"2020-05-10T18:46:50.931Z","started_at":"2020-05-10T18:56:18.895Z","finished_at":"2020-05-10T18:59:04.835Z","duration":165.940673,"queued_duration":1.861741,"user":{"id":2256237,"username":"coqbot","name":"coqbot","state":"active","avatar_url":"https://gitlab.com/uploads/-/system/user/avatar/2256237/avatar.png","web_url":"https://gitlab.com/coqbot","created_at":"2018-04-28T07:53:57.210Z","bio":"Hello, I'm a bot.","location":"","public_email":"","skype":"","linkedin":"","twitter":"","website_url":"","organization":"","job_title":"","pronouns":null,"bot":false,"work_information":null,"followers":0,"following":0,"local_time":null},"commit":{"id":"9bd08e99256614045cc9ef1f32a6a7b4fec56d50","short_id":"9bd08e99","created_at":"2020-05-10T20:42:16.000+02:00","parent_ids":["f40839ee880ac3e79d560e26f55f462f8ffd2e05"],"title":"[errors] Don't raise inside exception printers","message":"[errors] Don't raise inside exception printers\n\nThis is wrong and not properly handled anymore, instead the handlers\nare expected to return the error message.\n\nThis is a partial backport of #11498 , as it turns out this doesn't\nmake sense in 8.11 neither.\n\nFixes #12291\n","author_name":"Emilio Jesus Gallego Arias","author_email":"e+git@x80.org","authored_date":"2020-05-10T20:42:16.000+02:00","committer_name":"Emilio Jesus Gallego Arias","committer_email":"e+git@x80.org","committed_date":"2020-05-10T20:42:16.000+02:00","trailers":{},"web_url":"https://gitlab.com/coq/coq/-/commit/9bd08e99256614045cc9ef1f32a6a7b4fec56d50"},"pipeline":{"id":144552572,"iid":15987,"project_id":6138686,"sha":"9bd08e99256614045cc9ef1f32a6a7b4fec56d50","ref":"pr-12294","status":"failed","source":"push","created_at":"2020-05-10T18:46:50.220Z","updated_at":"2020-05-10T19:28:54.279Z","web_url":"https://gitlab.com/coq/coq/-/pipelines/144552572"},"web_url":"https://gitlab.com/coq/coq/-/jobs/545885239","artifacts":[{"file_type":"trace","size":45594,"filename":"job.log","file_format":null}],"runner":{"id":44028,"description":"shared-runners-manager-3.gitlab.com","ip_address":"35.196.21.178","active":true,"paused":false,"is_shared":true,"runner_type":"instance_type","name":"gitlab-runner","online":false,"status":"stale"},"artifacts_expire_at":null,"tag_list":[]}
{"id":545885238,"status":"success","stage":"stage-2","name":"plugin:ci-bignums","ref":"pr-12294","tag":false,"coverage":null,"allow_failure":false,"created_at":"2020-05-10T18:46:50.918Z","started_at":"2020-05-10T19:05:43.281Z","finished_at":"2020-05-10T19:09:42.335Z","duration":239.053773,"queued_duration":3.667006,"user":{"id":2256237,"username":"coqbot","name":"coqbot","state":"active","avatar_url":"https://gitlab.com/uploads/-/system/user/avatar/2256237/avatar.png","web_url":"https://gitlab.com/coqbot","created_at":"2018-04-28T07:53:57.210Z","bio":"Hello, I'm a bot.","location":"","public_email":"","skype":"","linkedin":"","twitter":"","website_url":"","organization":"","job_title":"","pronouns":null,"bot":false,"work_information":null,"followers":0,"following":0,"local_time":null},"commit":{"id":"9bd08e99256614045cc9ef1f32a6a7b4fec56d50","short_id":"9bd08e99","created_at":"2020-05-10T20:42:16.000+02:00","parent_ids":["f40839ee880ac3e79d560e26f55f462f8ffd2e05"],"title":"[errors] Don't raise inside exception printers","message":"[errors] Don't raise inside exception printers\n\nThis is wrong and not properly handled anymore, instead the handlers\nare expected to return the error message.\n\nThis is a partial backport of #11498 , as it turns out this doesn't\nmake sense in 8.11 neither.\n\nFixes #12291\n","author_name":"Emilio Jesus Gallego Arias","author_email":"e+git@x80.org","authored_date":"2020-05-10T20:42:16.000+02:00","committer_name":"Emilio Jesus Gallego Arias","committer_email":"e+git@x80.org","committed_date":"2020-05-10T20:42:16.000+02:00","trailers":{},"web_url":"https://gitlab.com/coq/coq/-/commit/9bd08e99256614045cc9ef1f32a6a7b4fec56d50"},"pipeline":{"id":144552572,"iid":15987,"project_id":6138686,"sha":"9bd08e99256614045cc9ef1f32a6a7b4fec56d50","ref":"pr-12294","status":"failed","source":"push","created_at":"2020-05-10T18:46:50.220Z","updated_at":"2020-05-10T19:28:54.279Z","web_url":"https://gitlab.com/coq/coq/-/pipelines/144552572"},"web_url":"https://gitlab.com/coq/coq/-/jobs/545885238","artifacts":[{"file_type":"trace","size":81001,"filename":"job.log","file_format":null}],"runner":null,"artifacts_expire_at":null,"tag_list":[]}
{"id":545885237,"status":"success","stage":"stage-2","name":"plugin:ci-aac_tactics","ref":"pr-12294","tag":false,"coverage":null,"allow_failure":false,"created_at":"2020-05-10T18:46:50.904Z","started_at":"2020-05-10T18:56:18.758Z","finished_at":"2020-05-10T18:59:20.861Z","duration":182.102738,"queued_duration":1.785737,"user":{"id":2256237,"username":"coqbot","name":"coqbot","state":"active","avatar_url":"https://gitlab.com/uploads/-/system/user/avatar/2256237/avatar.png","web_url":"https://gitlab.com/coqbot","created_at":"2018-04-28T07:53:57.210Z","bio":"Hello, I'm a bot.","location":"","public_email":"","skype":"","linkedin":"","twitter":"","website_url":"","organization":"","job_title":"","pronouns":null,"bot":false,"work_information":null,"followers":0,"following":0,"local_time":null},"commit":{"id":"9bd08e99256614045cc9ef1f32a6a7b4fec56d50","short_id":"9bd08e99","created_at":"2020-05-10T20:42:16.000+02:00","parent_ids":["f40839ee880ac3e79d560e26f55f462f8ffd2e05"],"title":"[errors] Don't raise inside exception printers","message":"[errors] Don't raise inside exception printers\n\nThis is wrong and not properly handled anymore, instead the handlers\nare expected to return the error message.\n\nThis is a partial backport of #11498 , as it turns out this doesn't\nmake sense in 8.11 neither.\n\nFixes #12291\n","author_name":"Emilio Jesus Gallego Arias","author_email":"e+git@x80.org","authored_date":"2020-05-10T20:42:16.000+02:00","committer_name":"Emilio Jesus Gallego Arias","committer_email":"e+git@x80.org","committed_date":"2020-05-10T20:42:16.000+02:00","trailers":{},"web_url":"https://gitlab.com/coq/coq/-/commit/9bd08e99256614045cc9ef1f32a6a7b4fec56d50"},"pipeline":{"id":144552572,"iid":15987,"project_id":6138686,"sha":"9bd08e99256614045cc9ef1f32a6a7b4fec56d50","ref":"pr-12294","status":"failed","source":"push","created_at":"2020-05-10T18:46:50.220Z","updated_at":"2020-05-10T19:28:54.279Z","web_url":"https://gitlab.com/coq/coq/-/pipelines/144552572"},"web_url":"https://gitlab.com/coq/coq/-/jobs/545885237","artifacts":[{"file_type":"trace","size":51101,"filename":"job.log","file_format":null}],"runner":{"id":44028,"description":"shared-runners-manager-3.gitlab.com","ip_address":"35.196.21.178","active":true,"paused":false,"is_shared":true,"runner_type":"instance_type","name":"gitlab-runner","online":false,"status":"stale"},"artifacts_expire_at":null,"tag_list":[]}
{"id":545885236,"status":"canceled","stage":"stage-2","name":"library:ci-vst","ref":"pr-12294","tag":false,"coverage":null,"allow_failure":false,"created_at":"2020-05-10T18:46:50.890Z","started_at":"2020-05-10T19:05:42.734Z","finished_at":"2020-05-10T19:28:53.999Z","duration":1391.264776,"queued_duration":3.172062,"user":{"id":2256237,"username":"coqbot","name":"coqbot","state":"active","avatar_url":"https://gitlab.com/uploads/-/system/user/avatar/2256237/avatar.png","web_url":"https://gitlab.com/coqbot","created_at":"2018-04-28T07:53:57.210Z","bio":"Hello, I'm a bot.","location":"","public_email":"","skype":"","linkedin":"","twitter":"","website_url":"","organization":"","job_title":"","pronouns":null,"bot":false,"work_information":null,"followers":0,"following":0,"local_time":null},"commit":{"id":"9bd08e99256614045cc9ef1f32a6a7b4fec56d50","short_id":"9bd08e99","created_at":"2020-05-10T20:42:16.000+02:00","parent_ids":["f40839ee880ac3e79d560e26f55f462f8ffd2e05"],"title":"[errors] Don't raise inside exception printers","message":"[errors] Don't raise inside exception printers\n\nThis is wrong and not properly handled anymore, instead the handlers\nare expected to return the error message.\n\nThis is a partial backport of #11498 , as it turns out this doesn't\nmake sense in 8.11 neither.\n\nFixes #12291\n","author_name":"Emilio Jesus Gallego Arias","author_email":"e+git@x80.org","authored_date":"2020-05-10T20:42:16.000+02:00","committer_name":"Emilio Jesus Gallego Arias","committer_email":"e+git@x80.org","committed_date":"2020-05-10T20:42:16.000+02:00","trailers":{},"web_url":"https://gitlab.com/coq/coq/-/commit/9bd08e99256614045cc9ef1f32a6a7b4fec56d50"},"pipeline":{"id":144552572,"iid":15987,"project_id":6138686,"sha":"9bd08e99256614045cc9ef1f32a6a7b4fec56d50","ref":"pr-12294","status":"failed","source":"push","created_at":"2020-05-10T18:46:50.220Z","updated_at":"2020-05-10T19:28:54.279Z","web_url":"https://gitlab.com/coq/coq/-/pipelines/144552572"},"web_url":"https://gitlab.com/coq/coq/-/jobs/545885236","artifacts":[{"file_type":"trace","size":133849,"filename":"job.log","file_format":null}],"runner":null,"artifacts_expire_at":null,"tag_list":[]}
{"id":545885235,"status":"canceled","stage":"stage-2","name":"library:ci-verdi-raft","ref":"pr-12294","tag":false,"coverage":null,"allow_failure":false,"created_at":"2020-05-10T18:46:50.877Z","started_at":"2020-05-10T19:05:42.498Z","finished_at":"2020-05-10T19:28:53.987Z","duration":1391.488975,"queued_duration":2.987265,"user":{"id":2256237,"username":"coqbot","name":"coqbot","state":"active","avatar_url":"https://gitlab.com/uploads/-/system/user/avatar/2256237/avatar.png","web_url":"https://gitlab.com/coqbot","created_at":"2018-04-28T07:53:57.210Z","bio":"Hello, I'm a bot.","location":"","public_email":"","skype":"","linkedin":"","twitter":"","website_url":"","organization":"","job_title":"","pronouns":null,"bot":false,"work_information":null,"followers":0,"following":0,"local_time":null},"commit":{"id":"9bd08e99256614045cc9ef1f32a6a7b4fec56d50","short_id":"9bd08e99","created_at":"2020-05-10T20:42:16.000+02:00","parent_ids":["f40839ee880ac3e79d560e26f55f462f8ffd2e05"],"title":"[errors] Don't raise inside exception printers","message":"[errors] Don't raise inside exception printers\n\nThis is wrong and not properly handled anymore, instead the handlers\nare expected to return the error message.\n\nThis is a partial backport of #11498 , as it turns out this doesn't\nmake sense in 8.11 neither.\n\nFixes #12291\n","author_name":"Emilio Jesus Gallego Arias","author_email":"e+git@x80.org","authored_date":"2020-05-10T20:42:16.000+02:00","committer_name":"Emilio Jesus Gallego Arias","committer_email":"e+git@x80.org","committed_date":"2020-05-10T20:42:16.000+02:00","trailers":{},"web_url":"https://gitlab.com/coq/coq/-/commit/9bd08e99256614045cc9ef1f32a6a7b4fec56d50"},"pipeline":{"id":144552572,"iid":15987,"project_id":6138686,"sha":"9bd08e99256614045cc9ef1f32a6a7b4fec56d50","ref":"pr-12294","status":"failed","source":"push","created_at":"2020-05-10T18:46:50.220Z","updated_at":"2020-05-10T19:28:54.279Z","web_url":"https://gitlab.com/coq/coq/-/pipelines/144552572"},"web_url":"https://gitlab.com/coq/coq/-/jobs/545885235","artifacts":[{"file_type":"trace","size":174011,"filename":"job.log","file_format":null}],"runner":null,"artifacts_expire_at":null,"tag_list":[]}
{"id":545885234,"status":"canceled","stage":"stage-2","name":"library:ci-unimath","ref":"pr-12294","tag":false,"coverage":null,"allow_failure":false,"created_at":"2020-05-10T18:46:50.864Z","started_at":"2020-05-10T19:05:42.352Z","finished_at":"2020-05-10T19:28:53.976Z","duration":1391.62438,"queued_duration":2.891251,"user":{"id":2256237,"username":"coqbot","name":"coqbot","state":"active","avatar_url":"https://gitlab.com/uploads/-/system/user/avatar/2256237/avatar.png","web_url":"https://gitlab.com/coqbot","created_at":"2018-04-28T07:53:57.210Z","bio":"Hello, I'm a bot.","location":"","public_email":"","skype":"","linkedin":"","twitter":"","website_url":"","organization":"","job_title":"","pronouns":null,"bot":false,"work_information":null,"followers":0,"following":0,"local_time":null},"commit":{"id":"9bd08e99256614045cc9ef1f32a6a7b4fec56d50","short_id":"9bd08e99","created_at":"2020-05-10T20:42:16.000+02:00","parent_ids":["f40839ee880ac3e79d560e26f55f462f8ffd2e05"],"title":"[errors] Don't raise inside exception printers","message":"[errors] Don't raise inside exception printers\n\nThis is wrong and not properly handled anymore, instead the handlers\nare expected to return the error message.\n\nThis is a partial backport of #11498 , as it turns out this doesn't\nmake sense in 8.11 neither.\n\nFixes #12291\n","author_name":"Emilio Jesus Gallego Arias","author_email":"e+git@x80.org","authored_date":"2020-05-10T20:42:16.000+02:00","committer_name":"Emilio Jesus Gallego Arias","committer_email":"e+git@x80.org","committed_date":"2020-05-10T20:42:16.000+02:00","trailers":{},"web_url":"https://gitlab.com/coq/coq/-/commit/9bd08e99256614045cc9ef1f32a6a7b4fec56d50"},"pipeline":{"id":144552572,"iid":15987,"project_id":6138686,"sha":"9bd08e99256614045cc9ef1f32a6a7b4fec56d50","ref":"pr-12294","status":"failed","source":"push","created_at":"2020-05-10T18:46:50.220Z","updated_at":"2020-05-10T19:28:54.279Z","web_url":"https://gitlab.com/coq/coq/-/pipelines/144552572"},"web_url":"https://gitlab.com/coq/coq/-/jobs/545885234","artifacts":[{"file_type":"trace","size":177447,"filename":"job.log","file_format":null}],"runner":null,"artifacts_expire_at":null,"tag_list":[]}
{"id":545885233,"status":"success","stage":"stage-2","name":"library:ci-tlc","ref":"pr-12294","tag":false,"coverage":null,"allow_failure":false,"created_at":"2020-05-10T18:46:50.850Z","started_at":"2020-05-10T18:56:18.719Z","finished_at":"2020-05-10T19:00:33.682Z","duration":254.963166,"queued_duration":1.79811,"user":{"id":2256237,"username":"coqbot","name":"coqbot","state":"active","avatar_url":"https://gitlab.com/uploads/-/system/user/avatar/2256237/avatar.png","web_url":"https://gitlab.com/coqbot","created_at":"2018-04-28T07:53:57.210Z","bio":"Hello, I'm a bot.","location":"","public_email":"","skype":"","linkedin":"","twitter":"","website_url":"","organization":"","job_title":"","pronouns":null,"bot":false,"work_information":null,"followers":0,"following":0,"local_time":null},"commit":{"id":"9bd08e99256614045cc9ef1f32a6a7b4fec56d50","short_id":"9bd08e99","created_at":"2020-05-10T20:42:16.000+02:00","parent_ids":["f40839ee880ac3e79d560e26f55f462f8ffd2e05"],"title":"[errors] Don't raise inside exception printers","message":"[errors] Don't raise inside exception printers\n\nThis is wrong and not properly handled anymore, instead the handlers\nare expected to return the error message.\n\nThis is a partial backport of #11498 , as it turns out this doesn't\nmake sense in 8.11 neither.\n\nFixes #12291\n","author_name":"Emilio Jesus Gallego Arias","author_email":"e+git@x80.org","authored_date":"2020-05-10T20:42:16.000+02:00","committer_name":"Emilio Jesus Gallego Arias","committer_email":"e+git@x80.org","committed_date":"2020-05-10T20:42:16.000+02:00","trailers":{},"web_url":"https://gitlab.com/coq/coq/-/commit/9bd08e99256614045cc9ef1f32a6a7b4fec56d50"},"pipeline":{"id":144552572,"iid":15987,"project_id":6138686,"sha":"9bd08e99256614045cc9ef1f32a6a7b4fec56d50","ref":"pr-12294","status":"failed","source":"push","created_at":"2020-05-10T18:46:50.220Z","updated_at":"2020-05-10T19:28:54.279Z","web_url":"https://gitlab.com/coq/coq/-/pipelines/144552572"},"web_url":"https://gitlab.com/coq/coq/-/jobs/545885233","artifacts":[{"file_type":"trace","size":34699,"filename":"job.log","file_format":null}],"runner":{"id":44949,"description":"shared-runners-manager-4.gitlab.com","ip_address":"13.37.237.197","active":true,"paused":false,"is_shared":true,"runner_type":"instance_type","name":"gitlab-runner","online":false,"status":"stale"},"artifacts_expire_at":null,"tag_list":[]}
{"id":545885232,"status":"success","stage":"stage-2","name":"library:ci-stdlib2","ref":"pr-12294","tag":false,"coverage":null,"allow_failure":false,"created_at":"2020-05-10T18:46:50.837Z","started_at":"2020-05-10T19:05:42.008Z","finished_at":"2020-05-10T19:07:15.916Z","duration":93.907637,"queued_duration":2.599959,"user":{"id":2256237,"username":"coqbot","name":"coqbot","state":"active","avatar_url":"https://gitlab.com/uploads/-/system/user/avatar/2256237/avatar.png","web_url":"https://gitlab.com/coqbot","created_at":"2018-04-28T07:53:57.210Z","bio":"Hello, I'm a bot.","location":"","public_email":"","skype":"","linkedin":"","twitter":"","website_url":"","organization":"","job_title":"","pronouns":null,"bot":false,"work_information":null,"followers":0,"following":0,"local_time":null},"commit":{"id":"9bd08e99256614045cc9ef1f32a6a7b4fec56d50","short_id":"9bd08e99","created_at":"2020-05-10T20:42:16.000+02:00","parent_ids":["f40839ee880ac3e79d560e26f55f462f8ffd2e05"],"title":"[errors] Don't raise inside exception printers","message":"[errors] Don't raise inside exception printers\n\nThis is wrong and not properly handled anymore, instead the handlers\nare expected to return the error message.\n\nThis is a partial backport of #11498 , as it turns out this doesn't\nmake sense in 8.11 neither.\n\nFixes #12291\n","author_name":"Emilio Jesus Gallego Arias","author_email":"e+git@x80.org","authored_date":"2020-05-10T20:42:16.000+02:00","committer_name":"Emilio Jesus Gallego Arias","committer_email":"e+git@x80.org","committed_date":"2020-05-10T20:42:16.000+02:00","trailers":{},"web_url":"https://gitlab.com/coq/coq/-/commit/9bd08e99256614045cc9ef1f32a6a7b4fec56d50"},"pipeline":{"id":144552572,"iid":15987,"project_id":6138686,"sha":"9bd08e99256614045cc9ef1f32a6a7b4fec56d50","ref":"pr-12294","status":"failed","source":"push","created_at":"2020-05-10T18:46:50.220Z","updated_at":"2020-05-10T19:28:54.279Z","web_url":"https://gitlab.com/coq/coq/-/pipelines/144552572"},"web_url":"https://gitlab.com/coq/coq/-/jobs/545885232","artifacts":[{"file_type":"trace","size":73684,"filename":"job.log","file_format":null}],"runner":null,"artifacts_expire_at":null,"tag_list":[]}
{"id":545885231,"status":"failed","stage":"stage-2","name":"library:ci-sf","ref":"pr-12294","tag":false,"coverage":null,"allow_failure":false,"created_at":"2020-05-10T18:46:50.818Z","started_at":"2020-05-10T18:56:18.678Z","finished_at":"2020-05-10T18:59:01.860Z","duration":163.182364,"queued_duration":1.812073,"user":{"id":2256237,"username":"coqbot","name":"coqbot","state":"active","avatar_url":"https://gitlab.com/uploads/-/system/user/avatar/2256237/avatar.png","web_url":"https://gitlab.com/coqbot","created_at":"2018-04-28T07:53:57.210Z","bio":"Hello, I'm a bot.","location":"","public_email":"","skype":"","linkedin":"","twitter":"","website_url":"","organization":"","job_title":"","pronouns":null,"bot":false,"work_information":null,"followers":0,"following":0,"local_time":null},"commit":{"id":"9bd08e99256614045cc9ef1f32a6a7b4fec56d50","short_id":"9bd08e99","created_at":"2020-05-10T20:42:16.000+02:00","parent_ids":["f40839ee880ac3e79d560e26f55f462f8ffd2e05"],"title":"[errors] Don't raise inside exception printers","message":"[errors] Don't raise inside exception printers\n\nThis is wrong and not properly handled anymore, instead the handlers\nare expected to return the error message.\n\nThis is a partial backport of #11498 , as it turns out this doesn't\nmake sense in 8.11 neither.\n\nFixes #12291\n","author_name":"Emilio Jesus Gallego Arias","author_email":"e+git@x80.org","authored_date":"2020-05-10T20:42:16.000+02:00","committer_name":"Emilio Jesus Gallego Arias","committer_email":"e+git@x80.org","committed_date":"2020-05-10T20:42:16.000+02:00","trailers":{},"web_url":"https://gitlab.com/coq/coq/-/commit/9bd08e99256614045cc9ef1f32a6a7b4fec56d50"},"pipeline":{"id":144552572,"iid":15987,"project_id":6138686,"sha":"9bd08e99256614045cc9ef1f32a6a7b4fec56d50","ref":"pr-12294","status":"failed","source":"push","created_at":"2020-05-10T18:46:50.220Z","updated_at":"2020-05-10T19:28:54.279Z","web_url":"https://gitlab.com/coq/coq/-/pipelines/144552572"},"failure_reason":"script_failure","web_url":"https://gitlab.com/coq/coq/-/jobs/545885231","artifacts":[{"file_type":"trace","size":26009,"filename":"job.log","file_format":null}],"runner":{"id":380986,"description":"shared-runners-manager-5.gitlab.com","ip_address":"34.74.209.140","active":true,"paused":false,"is_shared":true,"runner_type":"instance_type","name":"gitlab-runner","online":false,"status":"stale"},"artifacts_expire_at":null,"tag_list":[]}
{"id":545885230,"status":"canceled","stage":"stage-2","name":"library:ci-math-comp","ref":"pr-12294","tag":false,"coverage":null,"allow_failure":false,"created_at":"2020-05-10T18:46:50.804Z","started_at":"2020-05-10T19:05:41.954Z","finished_at":"2020-05-10T19:28:53.966Z","duration":1392.011336,"queued_duration":2.596648,"user":{"id":2256237,"username":"coqbot","name":"coqbot","state":"active","avatar_url":"https://gitlab.com/uploads/-/system/user/avatar/2256237/avatar.png","web_url":"https://gitlab.com/coqbot","created_at":"2018-04-28T07:53:57.210Z","bio":"Hello, I'm a bot.","location":"","public_email":"","skype":"","linkedin":"","twitter":"","website_url":"","organization":"","job_title":"","pronouns":null,"bot":false,"work_information":null,"followers":0,"following":0,"local_time":null},"commit":{"id":"9bd08e99256614045cc9ef1f32a6a7b4fec56d50","short_id":"9bd08e99","created_at":"2020-05-10T20:42:16.000+02:00","parent_ids":["f40839ee880ac3e79d560e26f55f462f8ffd2e05"],"title":"[errors] Don't raise inside exception printers","message":"[errors] Don't raise inside exception printers\n\nThis is wrong and not properly handled anymore, instead the handlers\nare expected to return the error message.\n\nThis is a partial backport of #11498 , as it turns out this doesn't\nmake sense in 8.11 neither.\n\nFixes #12291\n","author_name":"Emilio Jesus Gallego Arias","author_email":"e+git@x80.org","authored_date":"2020-05-10T20:42:16.000+02:00","committer_name":"Emilio Jesus Gallego Arias","committer_email":"e+git@x80.org","committed_date":"2020-05-10T20:42:16.000+02:00","trailers":{},"web_url":"https://gitlab.com/coq/coq/-/commit/9bd08e99256614045cc9ef1f32a6a7b4fec56d50"},"pipeline":{"id":144552572,"iid":15987,"project_id":6138686,"sha":"9bd08e99256614045cc9ef1f32a6a7b4fec56d50","ref":"pr-12294","status":"failed","source":"push","created_at":"2020-05-10T18:46:50.220Z","updated_at":"2020-05-10T19:28:54.279Z","web_url":"https://gitlab.com/coq/coq/-/pipelines/144552572"},"web_url":"https://gitlab.com/coq/coq/-/jobs/545885230","artifacts":[{"file_type":"trace","size":265675,"filename":"job.log","file_format":null}],"runner":null,"artifacts_expire_at":null,"tag_list":[]}
{"id":545885229,"status":"canceled","stage":"stage-2","name":"library:ci-iris-lambda-rust","ref":"pr-12294","tag":false,"coverage":null,"allow_failure":false,"created_at":"2020-05-10T18:46:50.790Z","started_at":"2020-05-10T19:05:41.647Z","finished_at":"2020-05-10T19:28:53.955Z","duration":1392.308266,"queued_duration":2.341366,"user":{"id":2256237,"username":"coqbot","name":"coqbot","state":"active","avatar_url":"https://gitlab.com/uploads/-/system/user/avatar/2256237/avatar.png","web_url":"https://gitlab.com/coqbot","created_at":"2018-04-28T07:53:57.210Z","bio":"Hello, I'm a bot.","location":"","public_email":"","skype":"","linkedin":"","twitter":"","website_url":"","organization":"","job_title":"","pronouns":null,"bot":false,"work_information":null,"followers":0,"following":0,"local_time":null},"commit":{"id":"9bd08e99256614045cc9ef1f32a6a7b4fec56d50","short_id":"9bd08e99","created_at":"2020-05-10T20:42:16.000+02:00","parent_ids":["f40839ee880ac3e79d560e26f55f462f8ffd2e05"],"title":"[errors] Don't raise inside exception printers","message":"[errors] Don't raise inside exception printers\n\nThis is wrong and not properly handled anymore, instead the handlers\nare expected to return the error message.\n\nThis is a partial backport of #11498 , as it turns out this doesn't\nmake sense in 8.11 neither.\n\nFixes #12291\n","author_name":"Emilio Jesus Gallego Arias","author_email":"e+git@x80.org","authored_date":"2020-05-10T20:42:16.000+02:00","committer_name":"Emilio Jesus Gallego Arias","committer_email":"e+git@x80.org","committed_date":"2020-05-10T20:42:16.000+02:00","trailers":{},"web_url":"https://gitlab.com/coq/coq/-/commit/9bd08e99256614045cc9ef1f32a6a7b4fec56d50"},"pipeline":{"id":144552572,"iid":15987,"project_id":6138686,"sha":"9bd08e99256614045cc9ef1f32a6a7b4fec56d50","ref":"pr-12294","status":"failed","source":"push","created_at":"2020-05-10T18:46:50.220Z","updated_at":"2020-05-10T19:28:54.279Z","web_url":"https://gitlab.com/coq/coq/-/pipelines/144552572"},"web_url":"https://gitlab.com/coq/coq/-/jobs/545885229","artifacts":[{"file_type":"trace","size":247975,"filename":"job.log","file_format":null}],"runner":null,"artifacts_expire_at":null,"tag_list":[]}
{"id":545885228,"status":"success","stage":"stage-2","name":"library:ci-hott","ref":"pr-12294","tag":false,"coverage":null,"allow_failure":false,"created_at":"2020-05-10T18:46:50.776Z","started_at":"2020-05-10T18:56:18.640Z","finished_at":"2020-05-10T19:07:53.830Z","duration":695.189721,"queued_duration":1.826926,"user":{"id":2256237,"username":"coqbot","name":"coqbot","state":"active","avatar_url":"https://gitlab.com/uploads/-/system/user/avatar/2256237/avatar.png","web_url":"https://gitlab.com/coqbot","created_at":"2018-04-28T07:53:57.210Z","bio":"Hello, I'm a bot.","location":"","public_email":"","skype":"","linkedin":"","twitter":"","website_url":"","organization":"","job_title":"","pronouns":null,"bot":false,"work_information":null,"followers":0,"following":0,"local_time":null},"commit":{"id":"9bd08e99256614045cc9ef1f32a6a7b4fec56d50","short_id":"9bd08e99","created_at":"2020-05-10T20:42:16.000+02:00","parent_ids":["f40839ee880ac3e79d560e26f55f462f8ffd2e05"],"title":"[errors] Don't raise inside exception printers","message":"[errors] Don't raise inside exception printers\n\nThis is wrong and not properly handled anymore, instead the handlers\nare expected to return the error message.\n\nThis is a partial backport of #11498 , as it turns out this doesn't\nmake sense in 8.11 neither.\n\nFixes #12291\n","author_name":"Emilio Jesus Gallego Arias","author_email":"e+git@x80.org","authored_date":"2020-05-10T20:42:16.000+02:00","committer_name":"Emilio Jesus Gallego Arias","committer_email":"e+git@x80.org","committed_date":"2020-05-10T20:42:16.000+02:00","trailers":{},"web_url":"https://gitlab.com/coq/coq/-/commit/9bd08e99256614045cc9ef1f32a6a7b4fec56d50"},"pipeline":{"id":144552572,"iid":15987,"project_id":6138686,"sha":"9bd08e99256614045cc9ef1f32a6a7b4fec56d50","ref":"pr-12294","status":"failed","source":"push","created_at":"2020-05-10T18:46:50.220Z","updated_at":"2020-05-10T19:28:54.279Z","web_url":"https://gitlab.com/coq/coq/-/pipelines/144552572"},"web_url":"https://gitlab.com/coq/coq/-/jobs/545885228","artifacts":[{"file_type":"trace","size":148255,"filename":"job.log","file_format":null}],"runner":null,"artifacts_expire_at":null,"tag_list":[]}
{"id":545885227,"status":"canceled","stage":"stage-2","name":"library:ci-geocoq","ref":"pr-12294","tag":false,"coverage":null,"allow_failure":false,"created_at":"2020-05-10T18:46:50.762Z","started_at":"2020-05-10T19:05:41.587Z","finished_at":"2020-05-10T19:28:53.946Z","duration":1392.358811,"queued_duration":2.330201,"user":{"id":2256237,"username":"coqbot","name":"coqbot","state":"active","avatar_url":"https://gitlab.com/uploads/-/system/user/avatar/2256237/avatar.png","web_url":"https://gitlab.com/coqbot","created_at":"2018-04-28T07:53:57.210Z","bio":"Hello, I'm a bot.","location":"","public_email":"","skype":"","linkedin":"","twitter":"","website_url":"","organization":"","job_title":"","pronouns":null,"bot":false,"work_information":null,"followers":0,"following":0,"local_time":null},"commit":{"id":"9bd08e99256614045cc9ef1f32a6a7b4fec56d50","short_id":"9bd08e99","created_at":"2020-05-10T20:42:16.000+02:00","parent_ids":["f40839ee880ac3e79d560e26f55f462f8ffd2e05"],"title":"[errors] Don't raise inside exception printers","message":"[errors] Don't raise inside exception printers\n\nThis is wrong and not properly handled anymore, instead the handlers\nare expected to return the error message.\n\nThis is a partial backport of #11498 , as it turns out this doesn't\nmake sense in 8.11 neither.\n\nFixes #12291\n","author_name":"Emilio Jesus Gallego Arias","author_email":"e+git@x80.org","authored_date":"2020-05-10T20:42:16.000+02:00","committer_name":"Emilio Jesus Gallego Arias","committer_email":"e+git@x80.org","committed_date":"2020-05-10T20:42:16.000+02:00","trailers":{},"web_url":"https://gitlab.com/coq/coq/-/commit/9bd08e99256614045cc9ef1f32a6a7b4fec56d50"},"pipeline":{"id":144552572,"iid":15987,"project_id":6138686,"sha":"9bd08e99256614045cc9ef1f32a6a7b4fec56d50","ref":"pr-12294","status":"failed","source":"push","created_at":"2020-05-10T18:46:50.220Z","updated_at":"2020-05-10T19:28:54.279Z","web_url":"https://gitlab.com/coq/coq/-/pipelines/144552572"},"web_url":"https://gitlab.com/coq/coq/-/jobs/545885227","artifacts":[{"file_type":"trace","size":467828,"filename":"job.log","file_format":null}],"runner":null,"artifacts_expire_at":null,"tag_list":[]}
{"id":545885226,"status":"success","stage":"stage-2","name":"library:ci-flocq","ref":"pr-12294","tag":false,"coverage":null,"allow_failure":false,"created_at":"2020-05-10T18:46:50.749Z","started_at":"2020-05-10T18:56:18.581Z","finished_at":"2020-05-10T19:03:21.412Z","duration":422.8307,"queued_duration":1.823947,"user":{"id":2256237,"username":"coqbot","name":"coqbot","state":"active","avatar_url":"https://gitlab.com/uploads/-/system/user/avatar/2256237/avatar.png","web_url":"https://gitlab.com/coqbot","created_at":"2018-04-28T07:53:57.210Z","bio":"Hello, I'm a bot.","location":"","public_email":"","skype":"","linkedin":"","twitter":"","website_url":"","organization":"","job_title":"","pronouns":null,"bot":false,"work_information":null,"followers":0,"following":0,"local_time":null},"commit":{"id":"9bd08e99256614045cc9ef1f32a6a7b4fec56d50","short_id":"9bd08e99","created_at":"2020-05-10T20:42:16.000+02:00","parent_ids":["f40839ee880ac3e79d560e26f55f462f8ffd2e05"],"title":"[errors] Don't raise inside exception printers","message":"[errors] Don't raise inside exception printers\n\nThis is wrong and not properly handled anymore, instead the handlers\nare expected to return the error message.\n\nThis is a partial backport of #11498 , as it turns out this doesn't\nmake sense in 8.11 neither.\n\nFixes #12291\n","author_name":"Emilio Jesus Gallego Arias","author_email":"e+git@x80.org","authored_date":"2020-05-10T20:42:16.000+02:00","committer_name":"Emilio Jesus Gallego Arias","committer_email":"e+git@x80.org","committed_date":"2020-05-10T20:42:16.000+02:00","trailers":{},"web_url":"https://gitlab.com/coq/coq/-/commit/9bd08e99256614045cc9ef1f32a6a7b4fec56d50"},"pipeline":{"id":144552572,"iid":15987,"project_id":6138686,"sha":"9bd08e99256614045cc9ef1f32a6a7b4fec56d50","ref":"pr-12294","status":"failed","source":"push","created_at":"2020-05-10T18:46:50.220Z","updated_at":"2020-05-10T19:28:54.279Z","web_url":"https://gitlab.com/coq/coq/-/pipelines/144552572"},"web_url":"https://gitlab.com/coq/coq/-/jobs/545885226","artifacts":[{"file_type":"trace","size":34989,"filename":"job.log","file_format":null}],"runner":{"id":380987,"description":"shared-runners-manager-6.gitlab.com","ip_address":"34.74.239.13","active":true,"paused":false,"is_shared":true,"runner_type":"instance_type","name":"gitlab-runner","online":false,"status":"stale"},"artifacts_expire_at":null,"tag_list":[]}
{"id":545885225,"status":"canceled","stage":"stage-2","name":"library:ci-fiat-crypto-legacy","ref":"pr-12294","tag":false,"coverage":null,"allow_failure":false,"created_at":"2020-05-10T18:46:50.733Z","started_at":"2020-05-10T19:05:41.294Z","finished_at":"2020-05-10T19:28:53.935Z","duration":1392.641183,"queued_duration":2.085868,"user":{"id":2256237,"username":"coqbot","name":"coqbot","state":"active","avatar_url":"https://gitlab.com/uploads/-/system/user/avatar/2256237/avatar.png","web_url":"https://gitlab.com/coqbot","created_at":"2018-04-28T07:53:57.210Z","bio":"Hello, I'm a bot.","location":"","public_email":"","skype":"","linkedin":"","twitter":"","website_url":"","organization":"","job_title":"","pronouns":null,"bot":false,"work_information":null,"followers":0,"following":0,"local_time":null},"commit":{"id":"9bd08e99256614045cc9ef1f32a6a7b4fec56d50","short_id":"9bd08e99","created_at":"2020-05-10T20:42:16.000+02:00","parent_ids":["f40839ee880ac3e79d560e26f55f462f8ffd2e05"],"title":"[errors] Don't raise inside exception printers","message":"[errors] Don't raise inside exception printers\n\nThis is wrong and not properly handled anymore, instead the handlers\nare expected to return the error message.\n\nThis is a partial backport of #11498 , as it turns out this doesn't\nmake sense in 8.11 neither.\n\nFixes #12291\n","author_name":"Emilio Jesus Gallego Arias","author_email":"e+git@x80.org","authored_date":"2020-05-10T20:42:16.000+02:00","committer_name":"Emilio Jesus Gallego Arias","committer_email":"e+git@x80.org","committed_date":"2020-05-10T20:42:16.000+02:00","trailers":{},"web_url":"https://gitlab.com/coq/coq/-/commit/9bd08e99256614045cc9ef1f32a6a7b4fec56d50"},"pipeline":{"id":144552572,"iid":15987,"project_id":6138686,"sha":"9bd08e99256614045cc9ef1f32a6a7b4fec56d50","ref":"pr-12294","status":"failed","source":"push","created_at":"2020-05-10T18:46:50.220Z","updated_at":"2020-05-10T19:28:54.279Z","web_url":"https://gitlab.com/coq/coq/-/pipelines/144552572"},"web_url":"https://gitlab.com/coq/coq/-/jobs/545885225","artifacts":[{"file_type":"trace","size":337556,"filename":"job.log","file_format":null}],"runner":null,"artifacts_expire_at":null,"tag_list":[]}
{"id":545885224,"status":"canceled","stage":"stage-2","name":"library:ci-fiat-crypto","ref":"pr-12294","tag":false,"coverage":null,"allow_failure":false,"created_at":"2020-05-10T18:46:50.719Z","started_at":"2020-05-10T19:05:41.231Z","finished_at":"2020-05-10T19:28:53.925Z","duration":1392.693965,"queued_duration":2.076645,"user":{"id":2256237,"username":"coqbot","name":"coqbot","state":"active","avatar_url":"https://gitlab.com/uploads/-/system/user/avatar/2256237/avatar.png","web_url":"https://gitlab.com/coqbot","created_at":"2018-04-28T07:53:57.210Z","bio":"Hello, I'm a bot.","location":"","public_email":"","skype":"","linkedin":"","twitter":"","website_url":"","organization":"","job_title":"","pronouns":null,"bot":false,"work_information":null,"followers":0,"following":0,"local_time":null},"commit":{"id":"9bd08e99256614045cc9ef1f32a6a7b4fec56d50","short_id":"9bd08e99","created_at":"2020-05-10T20:42:16.000+02:00","parent_ids":["f40839ee880ac3e79d560e26f55f462f8ffd2e05"],"title":"[errors] Don't raise inside exception printers","message":"[errors] Don't raise inside exception printers\n\nThis is wrong and not properly handled anymore, instead the handlers\nare expected to return the error message.\n\nThis is a partial backport of #11498 , as it turns out this doesn't\nmake sense in 8.11 neither.\n\nFixes #12291\n","author_name":"Emilio Jesus Gallego Arias","author_email":"e+git@x80.org","authored_date":"2020-05-10T20:42:16.000+02:00","committer_name":"Emilio Jesus Gallego Arias","committer_email":"e+git@x80.org","committed_date":"2020-05-10T20:42:16.000+02:00","trailers":{},"web_url":"https://gitlab.com/coq/coq/-/commit/9bd08e99256614045cc9ef1f32a6a7b4fec56d50"},"pipeline":{"id":144552572,"iid":15987,"project_id":6138686,"sha":"9bd08e99256614045cc9ef1f32a6a7b4fec56d50","ref":"pr-12294","status":"failed","source":"push","created_at":"2020-05-10T18:46:50.220Z","updated_at":"2020-05-10T19:28:54.279Z","web_url":"https://gitlab.com/coq/coq/-/pipelines/144552572"},"web_url":"https://gitlab.com/coq/coq/-/jobs/545885224","artifacts":[{"file_type":"trace","size":365661,"filename":"job.log","file_format":null}],"runner":null,"artifacts_expire_at":null,"tag_list":[]}
{"id":545885223,"status":"success","stage":"stage-2","name":"library:ci-fcsl-pcm","ref":"pr-12294","tag":false,"coverage":null,"allow_failure":false,"created_at":"2020-05-10T18:46:50.704Z","started_at":"2020-05-10T18:56:18.543Z","finished_at":"2020-05-10T19:00:51.488Z","duration":272.945483,"queued_duration":1.833942,"user":{"id":2256237,"username":"coqbot","name":"coqbot","state":"active","avatar_url":"https://gitlab.com/uploads/-/system/user/avatar/2256237/avatar.png","web_url":"https://gitlab.com/coqbot","created_at":"2018-04-28T07:53:57.210Z","bio":"Hello, I'm a bot.","location":"","public_email":"","skype":"","linkedin":"","twitter":"","website_url":"","organization":"","job_title":"","pronouns":null,"bot":false,"work_information":null,"followers":0,"following":0,"local_time":null},"commit":{"id":"9bd08e99256614045cc9ef1f32a6a7b4fec56d50","short_id":"9bd08e99","created_at":"2020-05-10T20:42:16.000+02:00","parent_ids":["f40839ee880ac3e79d560e26f55f462f8ffd2e05"],"title":"[errors] Don't raise inside exception printers","message":"[errors] Don't raise inside exception printers\n\nThis is wrong and not properly handled anymore, instead the handlers\nare expected to return the error message.\n\nThis is a partial backport of #11498 , as it turns out this doesn't\nmake sense in 8.11 neither.\n\nFixes #12291\n","author_name":"Emilio Jesus Gallego Arias","author_email":"e+git@x80.org","authored_date":"2020-05-10T20:42:16.000+02:00","committer_name":"Emilio Jesus Gallego Arias","committer_email":"e+git@x80.org","committed_date":"2020-05-10T20:42:16.000+02:00","trailers":{},"web_url":"https://gitlab.com/coq/coq/-/commit/9bd08e99256614045cc9ef1f32a6a7b4fec56d50"},"pipeline":{"id":144552572,"iid":15987,"project_id":6138686,"sha":"9bd08e99256614045cc9ef1f32a6a7b4fec56d50","ref":"pr-12294","status":"failed","source":"push","created_at":"2020-05-10T18:46:50.220Z","updated_at":"2020-05-10T19:28:54.279Z","web_url":"https://gitlab.com/coq/coq/-/pipelines/144552572"},"web_url":"https://gitlab.com/coq/coq/-/jobs/545885223","artifacts":[{"file_type":"trace","size":101253,"filename":"job.log","file_format":null}],"runner":{"id":380987,"description":"shared-runners-manager-6.gitlab.com","ip_address":"34.74.239.13","active":true,"paused":false,"is_shared":true,"runner_type":"instance_type","name":"gitlab-runner","online":false,"status":"stale"},"artifacts_expire_at":null,"tag_list":[]}
{"id":545885222,"status":"canceled","stage":"stage-2","name":"library:ci-cross-crypto","ref":"pr-12294","tag":false,"coverage":null,"allow_failure":false,"created_at":"2020-05-10T18:46:50.690Z","started_at":"2020-05-10T18:56:18.504Z","finished_at":"2020-05-10T19:28:53.915Z","duration":1955.411872,"queued_duration":1.850389,"user":{"id":2256237,"username":"coqbot","name":"coqbot","state":"active","avatar_url":"https://gitlab.com/uploads/-/system/user/avatar/2256237/avatar.png","web_url":"https://gitlab.com/coqbot","created_at":"2018-04-28T07:53:57.210Z","bio":"Hello, I'm a bot.","location":"","public_email":"","skype":"","linkedin":"","twitter":"","website_url":"","organization":"","job_title":"","pronouns":null,"bot":false,"work_information":null,"followers":0,"following":0,"local_time":null},"commit":{"id":"9bd08e99256614045cc9ef1f32a6a7b4fec56d50","short_id":"9bd08e99","created_at":"2020-05-10T20:42:16.000+02:00","parent_ids":["f40839ee880ac3e79d560e26f55f462f8ffd2e05"],"title":"[errors] Don't raise inside exception printers","message":"[errors] Don't raise inside exception printers\n\nThis is wrong and not properly handled anymore, instead the handlers\nare expected to return the error message.\n\nThis is a partial backport of #11498 , as it turns out this doesn't\nmake sense in 8.11 neither.\n\nFixes #12291\n","author_name":"Emilio Jesus Gallego Arias","author_email":"e+git@x80.org","authored_date":"2020-05-10T20:42:16.000+02:00","committer_name":"Emilio Jesus Gallego Arias","committer_email":"e+git@x80.org","committed_date":"2020-05-10T20:42:16.000+02:00","trailers":{},"web_url":"https://gitlab.com/coq/coq/-/commit/9bd08e99256614045cc9ef1f32a6a7b4fec56d50"},"pipeline":{"id":144552572,"iid":15987,"project_id":6138686,"sha":"9bd08e99256614045cc9ef1f32a6a7b4fec56d50","ref":"pr-12294","status":"failed","source":"push","created_at":"2020-05-10T18:46:50.220Z","updated_at":"2020-05-10T19:28:54.279Z","web_url":"https://gitlab.com/coq/coq/-/pipelines/144552572"},"web_url":"https://gitlab.com/coq/coq/-/jobs/545885222","artifacts":[{"file_type":"trace","size":35119,"filename":"job.log","file_format":null}],"runner":{"id":44949,"description":"shared-runners-manager-4.gitlab.com","ip_address":"13.37.237.197","active":true,"paused":false,"is_shared":true,"runner_type":"instance_type","name":"gitlab-runner","online":false,"status":"stale"},"artifacts_expire_at":null,"tag_list":[]}
{"id":545885221,"status":"success","stage":"stage-2","name":"library:ci-coquelicot","ref":"pr-12294","tag":false,"coverage":null,"allow_failure":false,"created_at":"2020-05-10T18:46:50.677Z","started_at":"2020-05-10T18:56:18.392Z","finished_at":"2020-05-10T19:01:56.319Z","duration":337.927832,"queued_duration":1.790364,"user":{"id":2256237,"username":"coqbot","name":"coqbot","state":"active","avatar_url":"https://gitlab.com/uploads/-/system/user/avatar/2256237/avatar.png","web_url":"https://gitlab.com/coqbot","created_at":"2018-04-28T07:53:57.210Z","bio":"Hello, I'm a bot.","location":"","public_email":"","skype":"","linkedin":"","twitter":"","website_url":"","organization":"","job_title":"","pronouns":null,"bot":false,"work_information":null,"followers":0,"following":0,"local_time":null},"commit":{"id":"9bd08e99256614045cc9ef1f32a6a7b4fec56d50","short_id":"9bd08e99","created_at":"2020-05-10T20:42:16.000+02:00","parent_ids":["f40839ee880ac3e79d560e26f55f462f8ffd2e05"],"title":"[errors] Don't raise inside exception printers","message":"[errors] Don't raise inside exception printers\n\nThis is wrong and not properly handled anymore, instead the handlers\nare expected to return the error message.\n\nThis is a partial backport of #11498 , as it turns out this doesn't\nmake sense in 8.11 neither.\n\nFixes #12291\n","author_name":"Emilio Jesus Gallego Arias","author_email":"e+git@x80.org","authored_date":"2020-05-10T20:42:16.000+02:00","committer_name":"Emilio Jesus Gallego Arias","committer_email":"e+git@x80.org","committed_date":"2020-05-10T20:42:16.000+02:00","trailers":{},"web_url":"https://gitlab.com/coq/coq/-/commit/9bd08e99256614045cc9ef1f32a6a7b4fec56d50"},"pipeline":{"id":144552572,"iid":15987,"project_id":6138686,"sha":"9bd08e99256614045cc9ef1f32a6a7b4fec56d50","ref":"pr-12294","status":"failed","source":"push","created_at":"2020-05-10T18:46:50.220Z","updated_at":"2020-05-10T19:28:54.279Z","web_url":"https://gitlab.com/coq/coq/-/pipelines/144552572"},"web_url":"https://gitlab.com/coq/coq/-/jobs/545885221","artifacts":[{"file_type":"trace","size":131066,"filename":"job.log","file_format":null}],"runner":{"id":380986,"description":"shared-runners-manager-5.gitlab.com","ip_address":"34.74.209.140","active":true,"paused":false,"is_shared":true,"runner_type":"instance_type","name":"gitlab-runner","online":false,"status":"stale"},"artifacts_expire_at":null,"tag_list":[]}
{"id":545885220,"status":"success","stage":"stage-2","name":"library:ci-compcert","ref":"pr-12294","tag":false,"coverage":null,"allow_failure":false,"created_at":"2020-05-10T18:46:50.663Z","started_at":"2020-05-10T18:56:18.288Z","finished_at":"2020-05-10T19:13:49.585Z","duration":1051.297666,"queued_duration":1.739004,"user":{"id":2256237,"username":"coqbot","name":"coqbot","state":"active","avatar_url":"https://gitlab.com/uploads/-/system/user/avatar/2256237/avatar.png","web_url":"https://gitlab.com/coqbot","created_at":"2018-04-28T07:53:57.210Z","bio":"Hello, I'm a bot.","location":"","public_email":"","skype":"","linkedin":"","twitter":"","website_url":"","organization":"","job_title":"","pronouns":null,"bot":false,"work_information":null,"followers":0,"following":0,"local_time":null},"commit":{"id":"9bd08e99256614045cc9ef1f32a6a7b4fec56d50","short_id":"9bd08e99","created_at":"2020-05-10T20:42:16.000+02:00","parent_ids":["f40839ee880ac3e79d560e26f55f462f8ffd2e05"],"title":"[errors] Don't raise inside exception printers","message":"[errors] Don't raise inside exception printers\n\nThis is wrong and not properly handled anymore, instead the handlers\nare expected to return the error message.\n\nThis is a partial backport of #11498 , as it turns out this doesn't\nmake sense in 8.11 neither.\n\nFixes #12291\n","author_name":"Emilio Jesus Gallego Arias","author_email":"e+git@x80.org","authored_date":"2020-05-10T20:42:16.000+02:00","committer_name":"Emilio Jesus Gallego Arias","committer_email":"e+git@x80.org","committed_date":"2020-05-10T20:42:16.000+02:00","trailers":{},"web_url":"https://gitlab.com/coq/coq/-/commit/9bd08e99256614045cc9ef1f32a6a7b4fec56d50"},"pipeline":{"id":144552572,"iid":15987,"project_id":6138686,"sha":"9bd08e99256614045cc9ef1f32a6a7b4fec56d50","ref":"pr-12294","status":"failed","source":"push","created_at":"2020-05-10T18:46:50.220Z","updated_at":"2020-05-10T19:28:54.279Z","web_url":"https://gitlab.com/coq/coq/-/pipelines/144552572"},"web_url":"https://gitlab.com/coq/coq/-/jobs/545885220","artifacts":[{"file_type":"trace","size":4194360,"filename":"job.log","file_format":null}],"runner":null,"artifacts_expire_at":null,"tag_list":[]}
{"id":545885219,"status":"canceled","stage":"stage-2","name":"library:ci-bedrock2","ref":"pr-12294","tag":false,"coverage":null,"allow_failure":false,"created_at":"2020-05-10T18:46:50.650Z","started_at":"2020-05-10T18:56:18.061Z","finished_at":"2020-05-10T19:28:53.905Z","duration":1955.844127,"queued_duration":1.5731,"user":{"id":2256237,"username":"coqbot","name":"coqbot","state":"active","avatar_url":"https://gitlab.com/uploads/-/system/user/avatar/2256237/avatar.png","web_url":"https://gitlab.com/coqbot","created_at":"2018-04-28T07:53:57.210Z","bio":"Hello, I'm a bot.","location":"","public_email":"","skype":"","linkedin":"","twitter":"","website_url":"","organization":"","job_title":"","pronouns":null,"bot":false,"work_information":null,"followers":0,"following":0,"local_time":null},"commit":{"id":"9bd08e99256614045cc9ef1f32a6a7b4fec56d50","short_id":"9bd08e99","created_at":"2020-05-10T20:42:16.000+02:00","parent_ids":["f40839ee880ac3e79d560e26f55f462f8ffd2e05"],"title":"[errors] Don't raise inside exception printers","message":"[errors] Don't raise inside exception printers\n\nThis is wrong and not properly handled anymore, instead the handlers\nare expected to return the error message.\n\nThis is a partial backport of #11498 , as it turns out this doesn't\nmake sense in 8.11 neither.\n\nFixes #12291\n","author_name":"Emilio Jesus Gallego Arias","author_email":"e+git@x80.org","authored_date":"2020-05-10T20:42:16.000+02:00","committer_name":"Emilio Jesus Gallego Arias","committer_email":"e+git@x80.org","committed_date":"2020-05-10T20:42:16.000+02:00","trailers":{},"web_url":"https://gitlab.com/coq/coq/-/commit/9bd08e99256614045cc9ef1f32a6a7b4fec56d50"},"pipeline":{"id":144552572,"iid":15987,"project_id":6138686,"sha":"9bd08e99256614045cc9ef1f32a6a7b4fec56d50","ref":"pr-12294","status":"failed","source":"push","created_at":"2020-05-10T18:46:50.220Z","updated_at":"2020-05-10T19:28:54.279Z","web_url":"https://gitlab.com/coq/coq/-/pipelines/144552572"},"web_url":"https://gitlab.com/coq/coq/-/jobs/545885219","artifacts":[{"file_type":"trace","size":94535,"filename":"job.log","file_format":null}],"runner":{"id":380986,"description":"shared-runners-manager-5.gitlab.com","ip_address":"34.74.209.140","active":true,"paused":false,"is_shared":true,"runner_type":"instance_type","name":"gitlab-runner","online":false,"status":"stale"},"artifacts_expire_at":null,"tag_list":[]}
{"id":545885218,"status":"success","stage":"stage-2","name":"library:ci-argosy","ref":"pr-12294","tag":false,"coverage":null,"allow_failure":false,"created_at":"2020-05-10T18:46:50.635Z","started_at":"2020-05-10T18:56:17.922Z","finished_at":"2020-05-10T18:58:50.406Z","duration":152.484294,"queued_duration":1.487255,"user":{"id":2256237,"username":"coqbot","name":"coqbot","state":"active","avatar_url":"https://gitlab.com/uploads/-/system/user/avatar/2256237/avatar.png","web_url":"https://gitlab.com/coqbot","created_at":"2018-04-28T07:53:57.210Z","bio":"Hello, I'm a bot.","location":"","public_email":"","skype":"","linkedin":"","twitter":"","website_url":"","organization":"","job_title":"","pronouns":null,"bot":false,"work_information":null,"followers":0,"following":0,"local_time":null},"commit":{"id":"9bd08e99256614045cc9ef1f32a6a7b4fec56d50","short_id":"9bd08e99","created_at":"2020-05-10T20:42:16.000+02:00","parent_ids":["f40839ee880ac3e79d560e26f55f462f8ffd2e05"],"title":"[errors] Don't raise inside exception printers","message":"[errors] Don't raise inside exception printers\n\nThis is wrong and not properly handled anymore, instead the handlers\nare expected to return the error message.\n\nThis is a partial backport of #11498 , as it turns out this doesn't\nmake sense in 8.11 neither.\n\nFixes #12291\n","author_name":"Emilio Jesus Gallego Arias","author_email":"e+git@x80.org","authored_date":"2020-05-10T20:42:16.000+02:00","committer_name":"Emilio Jesus Gallego Arias","committer_email":"e+git@x80.org","committed_date":"2020-05-10T20:42:16.000+02:00","trailers":{},"web_url":"https://gitlab.com/coq/coq/-/commit/9bd08e99256614045cc9ef1f32a6a7b4fec56d50"},"pipeline":{"id":144552572,"iid":15987,"project_id":6138686,"sha":"9bd08e99256614045cc9ef1f32a6a7b4fec56d50","ref":"pr-12294","status":"failed","source":"push","created_at":"2020-05-10T18:46:50.220Z","updated_at":"2020-05-10T19:28:54.279Z","web_url":"https://gitlab.com/coq/coq/-/pipelines/144552572"},"web_url":"https://gitlab.com/coq/coq/-/jobs/545885218","artifacts":[{"file_type":"trace","size":60392,"filename":"job.log","file_format":null}],"runner":null,"artifacts_expire_at":null,"tag_list":[]}
{"id":545885217,"status":"success","stage":"stage-2","name":"validate:quick","ref":"pr-12294","tag":false,"coverage":null,"allow_failure":false,"created_at":"2020-05-10T18:46:50.622Z","started_at":"2020-05-10T18:57:57.535Z","finished_at":"2020-05-10T19:02:20.492Z","duration":262.957065,"queued_duration":0.571643,"user":{"id":2256237,"username":"coqbot","name":"coqbot","state":"active","avatar_url":"https://gitlab.com/uploads/-/system/user/avatar/2256237/avatar.png","web_url":"https://gitlab.com/coqbot","created_at":"2018-04-28T07:53:57.210Z","bio":"Hello, I'm a bot.","location":"","public_email":"","skype":"","linkedin":"","twitter":"","website_url":"","organization":"","job_title":"","pronouns":null,"bot":false,"work_information":null,"followers":0,"following":0,"local_time":null},"commit":{"id":"9bd08e99256614045cc9ef1f32a6a7b4fec56d50","short_id":"9bd08e99","created_at":"2020-05-10T20:42:16.000+02:00","parent_ids":["f40839ee880ac3e79d560e26f55f462f8ffd2e05"],"title":"[errors] Don't raise inside exception printers","message":"[errors] Don't raise inside exception printers\n\nThis is wrong and not properly handled anymore, instead the handlers\nare expected to return the error message.\n\nThis is a partial backport of #11498 , as it turns out this doesn't\nmake sense in 8.11 neither.\n\nFixes #12291\n","author_name":"Emilio Jesus Gallego Arias","author_email":"e+git@x80.org","authored_date":"2020-05-10T20:42:16.000+02:00","committer_name":"Emilio Jesus Gallego Arias","committer_email":"e+git@x80.org","committed_date":"2020-05-10T20:42:16.000+02:00","trailers":{},"web_url":"https://gitlab.com/coq/coq/-/commit/9bd08e99256614045cc9ef1f32a6a7b4fec56d50"},"pipeline":{"id":144552572,"iid":15987,"project_id":6138686,"sha":"9bd08e99256614045cc9ef1f32a6a7b4fec56d50","ref":"pr-12294","status":"failed","source":"push","created_at":"2020-05-10T18:46:50.220Z","updated_at":"2020-05-10T19:28:54.279Z","web_url":"https://gitlab.com/coq/coq/-/pipelines/144552572"},"web_url":"https://gitlab.com/coq/coq/-/jobs/545885217","artifacts":[{"file_type":"trace","size":69160,"filename":"job.log","file_format":null}],"runner":{"id":44949,"description":"shared-runners-manager-4.gitlab.com","ip_address":"13.37.237.197","active":true,"paused":false,"is_shared":true,"runner_type":"instance_type","name":"gitlab-runner","online":false,"status":"stale"},"artifacts_expire_at":"2020-07-09T19:02:19.262Z","tag_list":[]}
{"id":545885216,"status":"success","stage":"stage-2","name":"validate:edge+flambda","ref":"pr-12294","tag":false,"coverage":null,"allow_failure":false,"created_at":"2020-05-10T18:46:50.609Z","started_at":"2020-05-10T19:05:40.870Z","finished_at":"2020-05-10T19:13:03.584Z","duration":442.714707,"queued_duration":1.7674,"user":{"id":2256237,"username":"coqbot","name":"coqbot","state":"active","avatar_url":"https://gitlab.com/uploads/-/system/user/avatar/2256237/avatar.png","web_url":"https://gitlab.com/coqbot","created_at":"2018-04-28T07:53:57.210Z","bio":"Hello, I'm a bot.","location":"","public_email":"","skype":"","linkedin":"","twitter":"","website_url":"","organization":"","job_title":"","pronouns":null,"bot":false,"work_information":null,"followers":0,"following":0,"local_time":null},"commit":{"id":"9bd08e99256614045cc9ef1f32a6a7b4fec56d50","short_id":"9bd08e99","created_at":"2020-05-10T20:42:16.000+02:00","parent_ids":["f40839ee880ac3e79d560e26f55f462f8ffd2e05"],"title":"[errors] Don't raise inside exception printers","message":"[errors] Don't raise inside exception printers\n\nThis is wrong and not properly handled anymore, instead the handlers\nare expected to return the error message.\n\nThis is a partial backport of #11498 , as it turns out this doesn't\nmake sense in 8.11 neither.\n\nFixes #12291\n","author_name":"Emilio Jesus Gallego Arias","author_email":"e+git@x80.org","authored_date":"2020-05-10T20:42:16.000+02:00","committer_name":"Emilio Jesus Gallego Arias","committer_email":"e+git@x80.org","committed_date":"2020-05-10T20:42:16.000+02:00","trailers":{},"web_url":"https://gitlab.com/coq/coq/-/commit/9bd08e99256614045cc9ef1f32a6a7b4fec56d50"},"pipeline":{"id":144552572,"iid":15987,"project_id":6138686,"sha":"9bd08e99256614045cc9ef1f32a6a7b4fec56d50","ref":"pr-12294","status":"failed","source":"push","created_at":"2020-05-10T18:46:50.220Z","updated_at":"2020-05-10T19:28:54.279Z","web_url":"https://gitlab.com/coq/coq/-/pipelines/144552572"},"web_url":"https://gitlab.com/coq/coq/-/jobs/545885216","artifacts":[{"file_type":"trace","size":159600,"filename":"job.log","file_format":null}],"runner":null,"artifacts_expire_at":"2020-07-09T19:13:00.790Z","tag_list":[]}
{"id":545885215,"status":"success","stage":"stage-2","name":"validate:base+32bit","ref":"pr-12294","tag":false,"coverage":null,"allow_failure":false,"created_at":"2020-05-10T18:46:50.595Z","started_at":"2020-05-10T18:58:24.589Z","finished_at":"2020-05-10T19:02:43.119Z","duration":258.529539,"queued_duration":0.652226,"user":{"id":2256237,"username":"coqbot","name":"coqbot","state":"active","avatar_url":"https://gitlab.com/uploads/-/system/user/avatar/2256237/avatar.png","web_url":"https://gitlab.com/coqbot","created_at":"2018-04-28T07:53:57.210Z","bio":"Hello, I'm a bot.","location":"","public_email":"","skype":"","linkedin":"","twitter":"","website_url":"","organization":"","job_title":"","pronouns":null,"bot":false,"work_information":null,"followers":0,"following":0,"local_time":null},"commit":{"id":"9bd08e99256614045cc9ef1f32a6a7b4fec56d50","short_id":"9bd08e99","created_at":"2020-05-10T20:42:16.000+02:00","parent_ids":["f40839ee880ac3e79d560e26f55f462f8ffd2e05"],"title":"[errors] Don't raise inside exception printers","message":"[errors] Don't raise inside exception printers\n\nThis is wrong and not properly handled anymore, instead the handlers\nare expected to return the error message.\n\nThis is a partial backport of #11498 , as it turns out this doesn't\nmake sense in 8.11 neither.\n\nFixes #12291\n","author_name":"Emilio Jesus Gallego Arias","author_email":"e+git@x80.org","authored_date":"2020-05-10T20:42:16.000+02:00","committer_name":"Emilio Jesus Gallego Arias","committer_email":"e+git@x80.org","committed_date":"2020-05-10T20:42:16.000+02:00","trailers":{},"web_url":"https://gitlab.com/coq/coq/-/commit/9bd08e99256614045cc9ef1f32a6a7b4fec56d50"},"pipeline":{"id":144552572,"iid":15987,"project_id":6138686,"sha":"9bd08e99256614045cc9ef1f32a6a7b4fec56d50","ref":"pr-12294","status":"failed","source":"push","created_at":"2020-05-10T18:46:50.220Z","updated_at":"2020-05-10T19:28:54.279Z","web_url":"https://gitlab.com/coq/coq/-/pipelines/144552572"},"web_url":"https://gitlab.com/coq/coq/-/jobs/545885215","artifacts":[{"file_type":"trace","size":67681,"filename":"job.log","file_format":null}],"runner":{"id":44949,"description":"shared-runners-manager-4.gitlab.com","ip_address":"13.37.237.197","active":true,"paused":false,"is_shared":true,"runner_type":"instance_type","name":"gitlab-runner","online":false,"status":"stale"},"artifacts_expire_at":"2020-07-09T19:02:41.848Z","tag_list":[]}
{"id":545885214,"status":"success","stage":"stage-2","name":"validate:base","ref":"pr-12294","tag":false,"coverage":null,"allow_failure":false,"created_at":"2020-05-10T18:46:50.582Z","started_at":"2020-05-10T18:56:17.577Z","finished_at":"2020-05-10T18:59:47.535Z","duration":209.958284,"queued_duration":1.194039,"user":{"id":2256237,"username":"coqbot","name":"coqbot","state":"active","avatar_url":"https://gitlab.com/uploads/-/system/user/avatar/2256237/avatar.png","web_url":"https://gitlab.com/coqbot","created_at":"2018-04-28T07:53:57.210Z","bio":"Hello, I'm a bot.","location":"","public_email":"","skype":"","linkedin":"","twitter":"","website_url":"","organization":"","job_title":"","pronouns":null,"bot":false,"work_information":null,"followers":0,"following":0,"local_time":null},"commit":{"id":"9bd08e99256614045cc9ef1f32a6a7b4fec56d50","short_id":"9bd08e99","created_at":"2020-05-10T20:42:16.000+02:00","parent_ids":["f40839ee880ac3e79d560e26f55f462f8ffd2e05"],"title":"[errors] Don't raise inside exception printers","message":"[errors] Don't raise inside exception printers\n\nThis is wrong and not properly handled anymore, instead the handlers\nare expected to return the error message.\n\nThis is a partial backport of #11498 , as it turns out this doesn't\nmake sense in 8.11 neither.\n\nFixes #12291\n","author_name":"Emilio Jesus Gallego Arias","author_email":"e+git@x80.org","authored_date":"2020-05-10T20:42:16.000+02:00","committer_name":"Emilio Jesus Gallego Arias","committer_email":"e+git@x80.org","committed_date":"2020-05-10T20:42:16.000+02:00","trailers":{},"web_url":"https://gitlab.com/coq/coq/-/commit/9bd08e99256614045cc9ef1f32a6a7b4fec56d50"},"pipeline":{"id":144552572,"iid":15987,"project_id":6138686,"sha":"9bd08e99256614045cc9ef1f32a6a7b4fec56d50","ref":"pr-12294","status":"failed","source":"push","created_at":"2020-05-10T18:46:50.220Z","updated_at":"2020-05-10T19:28:54.279Z","web_url":"https://gitlab.com/coq/coq/-/pipelines/144552572"},"web_url":"https://gitlab.com/coq/coq/-/jobs/545885214","artifacts":[{"file_type":"trace","size":110622,"filename":"job.log","file_format":null}],"runner":null,"artifacts_expire_at":"2020-07-09T18:59:45.520Z","tag_list":[]}
{"id":545885213,"status":"success","stage":"stage-2","name":"test-suite:base+async","ref":"pr-12294","tag":false,"coverage":null,"allow_failure":true,"created_at":"2020-05-10T18:46:50.565Z","started_at":"2020-05-10T18:56:17.240Z","finished_at":"2020-05-10T19:24:09.233Z","duration":1671.992844,"queued_duration":0.904433,"user":{"id":2256237,"username":"coqbot","name":"coqbot","state":"active","avatar_url":"https://gitlab.com/uploads/-/system/user/avatar/2256237/avatar.png","web_url":"https://gitlab.com/coqbot","created_at":"2018-04-28T07:53:57.210Z","bio":"Hello, I'm a bot.","location":"","public_email":"","skype":"","linkedin":"","twitter":"","website_url":"","organization":"","job_title":"","pronouns":null,"bot":false,"work_information":null,"followers":0,"following":0,"local_time":null},"commit":{"id":"9bd08e99256614045cc9ef1f32a6a7b4fec56d50","short_id":"9bd08e99","created_at":"2020-05-10T20:42:16.000+02:00","parent_ids":["f40839ee880ac3e79d560e26f55f462f8ffd2e05"],"title":"[errors] Don't raise inside exception printers","message":"[errors] Don't raise inside exception printers\n\nThis is wrong and not properly handled anymore, instead the handlers\nare expected to return the error message.\n\nThis is a partial backport of #11498 , as it turns out this doesn't\nmake sense in 8.11 neither.\n\nFixes #12291\n","author_name":"Emilio Jesus Gallego Arias","author_email":"e+git@x80.org","authored_date":"2020-05-10T20:42:16.000+02:00","committer_name":"Emilio Jesus Gallego Arias","committer_email":"e+git@x80.org","committed_date":"2020-05-10T20:42:16.000+02:00","trailers":{},"web_url":"https://gitlab.com/coq/coq/-/commit/9bd08e99256614045cc9ef1f32a6a7b4fec56d50"},"pipeline":{"id":144552572,"iid":15987,"project_id":6138686,"sha":"9bd08e99256614045cc9ef1f32a6a7b4fec56d50","ref":"pr-12294","status":"failed","source":"push","created_at":"2020-05-10T18:46:50.220Z","updated_at":"2020-05-10T19:28:54.279Z","web_url":"https://gitlab.com/coq/coq/-/pipelines/144552572"},"web_url":"https://gitlab.com/coq/coq/-/jobs/545885213","artifacts":[{"file_type":"trace","size":123346,"filename":"job.log","file_format":null}],"runner":null,"artifacts_expire_at":null,"tag_list":[]}
{"id":545885212,"status":"success","stage":"stage-2","name":"test-suite:edge:dune:dev","ref":"pr-12294","tag":false,"coverage":null,"allow_failure":false,"created_at":"2020-05-10T18:46:50.552Z","started_at":"2020-05-10T18:55:04.160Z","finished_at":"2020-05-10T19:17:00.398Z","duration":1316.23776,"queued_duration":0.847086,"user":{"id":2256237,"username":"coqbot","name":"coqbot","state":"active","avatar_url":"https://gitlab.com/uploads/-/system/user/avatar/2256237/avatar.png","web_url":"https://gitlab.com/coqbot","created_at":"2018-04-28T07:53:57.210Z","bio":"Hello, I'm a bot.","location":"","public_email":"","skype":"","linkedin":"","twitter":"","website_url":"","organization":"","job_title":"","pronouns":null,"bot":false,"work_information":null,"followers":0,"following":0,"local_time":null},"commit":{"id":"9bd08e99256614045cc9ef1f32a6a7b4fec56d50","short_id":"9bd08e99","created_at":"2020-05-10T20:42:16.000+02:00","parent_ids":["f40839ee880ac3e79d560e26f55f462f8ffd2e05"],"title":"[errors] Don't raise inside exception printers","message":"[errors] Don't raise inside exception printers\n\nThis is wrong and not properly handled anymore, instead the handlers\nare expected to return the error message.\n\nThis is a partial backport of #11498 , as it turns out this doesn't\nmake sense in 8.11 neither.\n\nFixes #12291\n","author_name":"Emilio Jesus Gallego Arias","author_email":"e+git@x80.org","authored_date":"2020-05-10T20:42:16.000+02:00","committer_name":"Emilio Jesus Gallego Arias","committer_email":"e+git@x80.org","committed_date":"2020-05-10T20:42:16.000+02:00","trailers":{},"web_url":"https://gitlab.com/coq/coq/-/commit/9bd08e99256614045cc9ef1f32a6a7b4fec56d50"},"pipeline":{"id":144552572,"iid":15987,"project_id":6138686,"sha":"9bd08e99256614045cc9ef1f32a6a7b4fec56d50","ref":"pr-12294","status":"failed","source":"push","created_at":"2020-05-10T18:46:50.220Z","updated_at":"2020-05-10T19:28:54.279Z","web_url":"https://gitlab.com/coq/coq/-/pipelines/144552572"},"web_url":"https://gitlab.com/coq/coq/-/jobs/545885212","artifacts":[{"file_type":"trace","size":94498,"filename":"job.log","file_format":null}],"runner":{"id":380987,"description":"shared-runners-manager-6.gitlab.com","ip_address":"34.74.239.13","active":true,"paused":false,"is_shared":true,"runner_type":"instance_type","name":"gitlab-runner","online":false,"status":"stale"},"artifacts_expire_at":null,"tag_list":[]}
{"id":545885211,"status":"success","stage":"stage-2","name":"test-suite:edge+flambda","ref":"pr-12294","tag":false,"coverage":null,"allow_failure":false,"created_at":"2020-05-10T18:46:50.539Z","started_at":"2020-05-10T19:05:39.461Z","finished_at":"2020-05-10T19:17:17.927Z","duration":698.466639,"queued_duration":0.410526,"user":{"id":2256237,"username":"coqbot","name":"coqbot","state":"active","avatar_url":"https://gitlab.com/uploads/-/system/user/avatar/2256237/avatar.png","web_url":"https://gitlab.com/coqbot","created_at":"2018-04-28T07:53:57.210Z","bio":"Hello, I'm a bot.","location":"","public_email":"","skype":"","linkedin":"","twitter":"","website_url":"","organization":"","job_title":"","pronouns":null,"bot":false,"work_information":null,"followers":0,"following":0,"local_time":null},"commit":{"id":"9bd08e99256614045cc9ef1f32a6a7b4fec56d50","short_id":"9bd08e99","created_at":"2020-05-10T20:42:16.000+02:00","parent_ids":["f40839ee880ac3e79d560e26f55f462f8ffd2e05"],"title":"[errors] Don't raise inside exception printers","message":"[errors] Don't raise inside exception printers\n\nThis is wrong and not properly handled anymore, instead the handlers\nare expected to return the error message.\n\nThis is a partial backport of #11498 , as it turns out this doesn't\nmake sense in 8.11 neither.\n\nFixes #12291\n","author_name":"Emilio Jesus Gallego Arias","author_email":"e+git@x80.org","authored_date":"2020-05-10T20:42:16.000+02:00","committer_name":"Emilio Jesus Gallego Arias","committer_email":"e+git@x80.org","committed_date":"2020-05-10T20:42:16.000+02:00","trailers":{},"web_url":"https://gitlab.com/coq/coq/-/commit/9bd08e99256614045cc9ef1f32a6a7b4fec56d50"},"pipeline":{"id":144552572,"iid":15987,"project_id":6138686,"sha":"9bd08e99256614045cc9ef1f32a6a7b4fec56d50","ref":"pr-12294","status":"failed","source":"push","created_at":"2020-05-10T18:46:50.220Z","updated_at":"2020-05-10T19:28:54.279Z","web_url":"https://gitlab.com/coq/coq/-/pipelines/144552572"},"web_url":"https://gitlab.com/coq/coq/-/jobs/545885211","artifacts":[{"file_type":"trace","size":98716,"filename":"job.log","file_format":null}],"runner":null,"artifacts_expire_at":null,"tag_list":[]}
{"id":545885210,"status":"success","stage":"stage-2","name":"test-suite:base+32bit","ref":"pr-12294","tag":false,"coverage":null,"allow_failure":false,"created_at":"2020-05-10T18:46:50.523Z","started_at":"2020-05-10T18:58:24.537Z","finished_at":"2020-05-10T19:16:53.450Z","duration":1108.913058,"queued_duration":0.661121,"user":{"id":2256237,"username":"coqbot","name":"coqbot","state":"active","avatar_url":"https://gitlab.com/uploads/-/system/user/avatar/2256237/avatar.png","web_url":"https://gitlab.com/coqbot","created_at":"2018-04-28T07:53:57.210Z","bio":"Hello, I'm a bot.","location":"","public_email":"","skype":"","linkedin":"","twitter":"","website_url":"","organization":"","job_title":"","pronouns":null,"bot":false,"work_information":null,"followers":0,"following":0,"local_time":null},"commit":{"id":"9bd08e99256614045cc9ef1f32a6a7b4fec56d50","short_id":"9bd08e99","created_at":"2020-05-10T20:42:16.000+02:00","parent_ids":["f40839ee880ac3e79d560e26f55f462f8ffd2e05"],"title":"[errors] Don't raise inside exception printers","message":"[errors] Don't raise inside exception printers\n\nThis is wrong and not properly handled anymore, instead the handlers\nare expected to return the error message.\n\nThis is a partial backport of #11498 , as it turns out this doesn't\nmake sense in 8.11 neither.\n\nFixes #12291\n","author_name":"Emilio Jesus Gallego Arias","author_email":"e+git@x80.org","authored_date":"2020-05-10T20:42:16.000+02:00","committer_name":"Emilio Jesus Gallego Arias","committer_email":"e+git@x80.org","committed_date":"2020-05-10T20:42:16.000+02:00","trailers":{},"web_url":"https://gitlab.com/coq/coq/-/commit/9bd08e99256614045cc9ef1f32a6a7b4fec56d50"},"pipeline":{"id":144552572,"iid":15987,"project_id":6138686,"sha":"9bd08e99256614045cc9ef1f32a6a7b4fec56d50","ref":"pr-12294","status":"failed","source":"push","created_at":"2020-05-10T18:46:50.220Z","updated_at":"2020-05-10T19:28:54.279Z","web_url":"https://gitlab.com/coq/coq/-/pipelines/144552572"},"web_url":"https://gitlab.com/coq/coq/-/jobs/545885210","artifacts":[{"file_type":"trace","size":91837,"filename":"job.log","file_format":null}],"runner":{"id":380987,"description":"shared-runners-manager-6.gitlab.com","ip_address":"34.74.239.13","active":true,"paused":false,"is_shared":true,"runner_type":"instance_type","name":"gitlab-runner","online":false,"status":"stale"},"artifacts_expire_at":null,"tag_list":[]}
{"id":545885209,"status":"success","stage":"stage-2","name":"test-suite:base","ref":"pr-12294","tag":false,"coverage":null,"allow_failure":false,"created_at":"2020-05-10T18:46:50.510Z","started_at":"2020-05-10T18:56:16.529Z","finished_at":"2020-05-10T19:11:21.243Z","duration":904.714512,"queued_duration":0.247942,"user":{"id":2256237,"username":"coqbot","name":"coqbot","state":"active","avatar_url":"https://gitlab.com/uploads/-/system/user/avatar/2256237/avatar.png","web_url":"https://gitlab.com/coqbot","created_at":"2018-04-28T07:53:57.210Z","bio":"Hello, I'm a bot.","location":"","public_email":"","skype":"","linkedin":"","twitter":"","website_url":"","organization":"","job_title":"","pronouns":null,"bot":false,"work_information":null,"followers":0,"following":0,"local_time":null},"commit":{"id":"9bd08e99256614045cc9ef1f32a6a7b4fec56d50","short_id":"9bd08e99","created_at":"2020-05-10T20:42:16.000+02:00","parent_ids":["f40839ee880ac3e79d560e26f55f462f8ffd2e05"],"title":"[errors] Don't raise inside exception printers","message":"[errors] Don't raise inside exception printers\n\nThis is wrong and not properly handled anymore, instead the handlers\nare expected to return the error message.\n\nThis is a partial backport of #11498 , as it turns out this doesn't\nmake sense in 8.11 neither.\n\nFixes #12291\n","author_name":"Emilio Jesus Gallego Arias","author_email":"e+git@x80.org","authored_date":"2020-05-10T20:42:16.000+02:00","committer_name":"Emilio Jesus Gallego Arias","committer_email":"e+git@x80.org","committed_date":"2020-05-10T20:42:16.000+02:00","trailers":{},"web_url":"https://gitlab.com/coq/coq/-/commit/9bd08e99256614045cc9ef1f32a6a7b4fec56d50"},"pipeline":{"id":144552572,"iid":15987,"project_id":6138686,"sha":"9bd08e99256614045cc9ef1f32a6a7b4fec56d50","ref":"pr-12294","status":"failed","source":"push","created_at":"2020-05-10T18:46:50.220Z","updated_at":"2020-05-10T19:28:54.279Z","web_url":"https://gitlab.com/coq/coq/-/pipelines/144552572"},"web_url":"https://gitlab.com/coq/coq/-/jobs/545885209","artifacts":[{"file_type":"trace","size":117428,"filename":"job.log","file_format":null}],"runner":null,"artifacts_expire_at":null,"tag_list":[]}
{"id":545885208,"status":"success","stage":"stage-2","name":"doc:ml-api:odoc","ref":"pr-12294","tag":false,"coverage":null,"allow_failure":false,"created_at":"2020-05-10T18:46:50.497Z","started_at":"2020-05-10T18:55:04.090Z","finished_at":"2020-05-10T18:58:45.430Z","duration":221.340018,"queued_duration":0.825382,"user":{"id":2256237,"username":"coqbot","name":"coqbot","state":"active","avatar_url":"https://gitlab.com/uploads/-/system/user/avatar/2256237/avatar.png","web_url":"https://gitlab.com/coqbot","created_at":"2018-04-28T07:53:57.210Z","bio":"Hello, I'm a bot.","location":"","public_email":"","skype":"","linkedin":"","twitter":"","website_url":"","organization":"","job_title":"","pronouns":null,"bot":false,"work_information":null,"followers":0,"following":0,"local_time":null},"commit":{"id":"9bd08e99256614045cc9ef1f32a6a7b4fec56d50","short_id":"9bd08e99","created_at":"2020-05-10T20:42:16.000+02:00","parent_ids":["f40839ee880ac3e79d560e26f55f462f8ffd2e05"],"title":"[errors] Don't raise inside exception printers","message":"[errors] Don't raise inside exception printers\n\nThis is wrong and not properly handled anymore, instead the handlers\nare expected to return the error message.\n\nThis is a partial backport of #11498 , as it turns out this doesn't\nmake sense in 8.11 neither.\n\nFixes #12291\n","author_name":"Emilio Jesus Gallego Arias","author_email":"e+git@x80.org","authored_date":"2020-05-10T20:42:16.000+02:00","committer_name":"Emilio Jesus Gallego Arias","committer_email":"e+git@x80.org","committed_date":"2020-05-10T20:42:16.000+02:00","trailers":{},"web_url":"https://gitlab.com/coq/coq/-/commit/9bd08e99256614045cc9ef1f32a6a7b4fec56d50"},"pipeline":{"id":144552572,"iid":15987,"project_id":6138686,"sha":"9bd08e99256614045cc9ef1f32a6a7b4fec56d50","ref":"pr-12294","status":"failed","source":"push","created_at":"2020-05-10T18:46:50.220Z","updated_at":"2020-05-10T19:28:54.279Z","web_url":"https://gitlab.com/coq/coq/-/pipelines/144552572"},"web_url":"https://gitlab.com/coq/coq/-/jobs/545885208","artifacts":[{"file_type":"trace","size":101600,"filename":"job.log","file_format":null}],"runner":null,"artifacts_expire_at":"2020-07-09T18:58:42.572Z","tag_list":[]}
{"id":545885207,"status":"success","stage":"stage-2","name":"doc:stdlib:dune","ref":"pr-12294","tag":false,"coverage":null,"allow_failure":false,"created_at":"2020-05-10T18:46:50.484Z","started_at":"2020-05-10T18:55:03.804Z","finished_at":"2020-05-10T18:59:48.315Z","duration":284.511153,"queued_duration":0.588186,"user":{"id":2256237,"username":"coqbot","name":"coqbot","state":"active","avatar_url":"https://gitlab.com/uploads/-/system/user/avatar/2256237/avatar.png","web_url":"https://gitlab.com/coqbot","created_at":"2018-04-28T07:53:57.210Z","bio":"Hello, I'm a bot.","location":"","public_email":"","skype":"","linkedin":"","twitter":"","website_url":"","organization":"","job_title":"","pronouns":null,"bot":false,"work_information":null,"followers":0,"following":0,"local_time":null},"commit":{"id":"9bd08e99256614045cc9ef1f32a6a7b4fec56d50","short_id":"9bd08e99","created_at":"2020-05-10T20:42:16.000+02:00","parent_ids":["f40839ee880ac3e79d560e26f55f462f8ffd2e05"],"title":"[errors] Don't raise inside exception printers","message":"[errors] Don't raise inside exception printers\n\nThis is wrong and not properly handled anymore, instead the handlers\nare expected to return the error message.\n\nThis is a partial backport of #11498 , as it turns out this doesn't\nmake sense in 8.11 neither.\n\nFixes #12291\n","author_name":"Emilio Jesus Gallego Arias","author_email":"e+git@x80.org","authored_date":"2020-05-10T20:42:16.000+02:00","committer_name":"Emilio Jesus Gallego Arias","committer_email":"e+git@x80.org","committed_date":"2020-05-10T20:42:16.000+02:00","trailers":{},"web_url":"https://gitlab.com/coq/coq/-/commit/9bd08e99256614045cc9ef1f32a6a7b4fec56d50"},"pipeline":{"id":144552572,"iid":15987,"project_id":6138686,"sha":"9bd08e99256614045cc9ef1f32a6a7b4fec56d50","ref":"pr-12294","status":"failed","source":"push","created_at":"2020-05-10T18:46:50.220Z","updated_at":"2020-05-10T19:28:54.279Z","web_url":"https://gitlab.com/coq/coq/-/pipelines/144552572"},"web_url":"https://gitlab.com/coq/coq/-/jobs/545885207","artifacts":[{"file_type":"trace","size":20535,"filename":"job.log","file_format":null}],"runner":{"id":44949,"description":"shared-runners-manager-4.gitlab.com","ip_address":"13.37.237.197","active":true,"paused":false,"is_shared":true,"runner_type":"instance_type","name":"gitlab-runner","online":false,"status":"stale"},"artifacts_expire_at":"2020-07-09T18:59:46.441Z","tag_list":[]}
{"id":545885206,"status":"success","stage":"stage-2","name":"doc:refman:dune","ref":"pr-12294","tag":false,"coverage":null,"allow_failure":false,"created_at":"2020-05-10T18:46:50.470Z","started_at":"2020-05-10T18:55:03.740Z","finished_at":"2020-05-10T19:01:15.191Z","duration":371.451164,"queued_duration":0.570877,"user":{"id":2256237,"username":"coqbot","name":"coqbot","state":"active","avatar_url":"https://gitlab.com/uploads/-/system/user/avatar/2256237/avatar.png","web_url":"https://gitlab.com/coqbot","created_at":"2018-04-28T07:53:57.210Z","bio":"Hello, I'm a bot.","location":"","public_email":"","skype":"","linkedin":"","twitter":"","website_url":"","organization":"","job_title":"","pronouns":null,"bot":false,"work_information":null,"followers":0,"following":0,"local_time":null},"commit":{"id":"9bd08e99256614045cc9ef1f32a6a7b4fec56d50","short_id":"9bd08e99","created_at":"2020-05-10T20:42:16.000+02:00","parent_ids":["f40839ee880ac3e79d560e26f55f462f8ffd2e05"],"title":"[errors] Don't raise inside exception printers","message":"[errors] Don't raise inside exception printers\n\nThis is wrong and not properly handled anymore, instead the handlers\nare expected to return the error message.\n\nThis is a partial backport of #11498 , as it turns out this doesn't\nmake sense in 8.11 neither.\n\nFixes #12291\n","author_name":"Emilio Jesus Gallego Arias","author_email":"e+git@x80.org","authored_date":"2020-05-10T20:42:16.000+02:00","committer_name":"Emilio Jesus Gallego Arias","committer_email":"e+git@x80.org","committed_date":"2020-05-10T20:42:16.000+02:00","trailers":{},"web_url":"https://gitlab.com/coq/coq/-/commit/9bd08e99256614045cc9ef1f32a6a7b4fec56d50"},"pipeline":{"id":144552572,"iid":15987,"project_id":6138686,"sha":"9bd08e99256614045cc9ef1f32a6a7b4fec56d50","ref":"pr-12294","status":"failed","source":"push","created_at":"2020-05-10T18:46:50.220Z","updated_at":"2020-05-10T19:28:54.279Z","web_url":"https://gitlab.com/coq/coq/-/pipelines/144552572"},"web_url":"https://gitlab.com/coq/coq/-/jobs/545885206","artifacts":[{"file_type":"trace","size":55356,"filename":"job.log","file_format":null}],"runner":null,"artifacts_expire_at":"2020-07-09T19:01:12.483Z","tag_list":[]}
{"id":545885205,"status":"success","stage":"stage-2","name":"doc:refman","ref":"pr-12294","tag":false,"coverage":null,"allow_failure":false,"created_at":"2020-05-10T18:46:50.442Z","started_at":"2020-05-10T18:56:16.425Z","finished_at":"2020-05-10T19:01:07.380Z","duration":290.954919,"queued_duration":0.196504,"user":{"id":2256237,"username":"coqbot","name":"coqbot","state":"active","avatar_url":"https://gitlab.com/uploads/-/system/user/avatar/2256237/avatar.png","web_url":"https://gitlab.com/coqbot","created_at":"2018-04-28T07:53:57.210Z","bio":"Hello, I'm a bot.","location":"","public_email":"","skype":"","linkedin":"","twitter":"","website_url":"","organization":"","job_title":"","pronouns":null,"bot":false,"work_information":null,"followers":0,"following":0,"local_time":null},"commit":{"id":"9bd08e99256614045cc9ef1f32a6a7b4fec56d50","short_id":"9bd08e99","created_at":"2020-05-10T20:42:16.000+02:00","parent_ids":["f40839ee880ac3e79d560e26f55f462f8ffd2e05"],"title":"[errors] Don't raise inside exception printers","message":"[errors] Don't raise inside exception printers\n\nThis is wrong and not properly handled anymore, instead the handlers\nare expected to return the error message.\n\nThis is a partial backport of #11498 , as it turns out this doesn't\nmake sense in 8.11 neither.\n\nFixes #12291\n","author_name":"Emilio Jesus Gallego Arias","author_email":"e+git@x80.org","authored_date":"2020-05-10T20:42:16.000+02:00","committer_name":"Emilio Jesus Gallego Arias","committer_email":"e+git@x80.org","committed_date":"2020-05-10T20:42:16.000+02:00","trailers":{},"web_url":"https://gitlab.com/coq/coq/-/commit/9bd08e99256614045cc9ef1f32a6a7b4fec56d50"},"pipeline":{"id":144552572,"iid":15987,"project_id":6138686,"sha":"9bd08e99256614045cc9ef1f32a6a7b4fec56d50","ref":"pr-12294","status":"failed","source":"push","created_at":"2020-05-10T18:46:50.220Z","updated_at":"2020-05-10T19:28:54.279Z","web_url":"https://gitlab.com/coq/coq/-/pipelines/144552572"},"web_url":"https://gitlab.com/coq/coq/-/jobs/545885205","artifacts":[{"file_type":"trace","size":1377770,"filename":"job.log","file_format":null}],"runner":null,"artifacts_expire_at":"2020-07-09T19:01:05.000Z","tag_list":[]}
{"id":545885204,"status":"success","stage":"stage-1","name":"plugin:plugin-tutorial","ref":"pr-12294","tag":false,"coverage":null,"allow_failure":false,"created_at":"2020-05-10T18:46:50.414Z","started_at":"2020-05-10T18:46:53.488Z","finished_at":"2020-05-10T18:50:55.244Z","duration":241.756263,"queued_duration":1.998922,"user":{"id":2256237,"username":"coqbot","name":"coqbot","state":"active","avatar_url":"https://gitlab.com/uploads/-/system/user/avatar/2256237/avatar.png","web_url":"https://gitlab.com/coqbot","created_at":"2018-04-28T07:53:57.210Z","bio":"Hello, I'm a bot.","location":"","public_email":"","skype":"","linkedin":"","twitter":"","website_url":"","organization":"","job_title":"","pronouns":null,"bot":false,"work_information":null,"followers":0,"following":0,"local_time":null},"commit":{"id":"9bd08e99256614045cc9ef1f32a6a7b4fec56d50","short_id":"9bd08e99","created_at":"2020-05-10T20:42:16.000+02:00","parent_ids":["f40839ee880ac3e79d560e26f55f462f8ffd2e05"],"title":"[errors] Don't raise inside exception printers","message":"[errors] Don't raise inside exception printers\n\nThis is wrong and not properly handled anymore, instead the handlers\nare expected to return the error message.\n\nThis is a partial backport of #11498 , as it turns out this doesn't\nmake sense in 8.11 neither.\n\nFixes #12291\n","author_name":"Emilio Jesus Gallego Arias","author_email":"e+git@x80.org","authored_date":"2020-05-10T20:42:16.000+02:00","committer_name":"Emilio Jesus Gallego Arias","committer_email":"e+git@x80.org","committed_date":"2020-05-10T20:42:16.000+02:00","trailers":{},"web_url":"https://gitlab.com/coq/coq/-/commit/9bd08e99256614045cc9ef1f32a6a7b4fec56d50"},"pipeline":{"id":144552572,"iid":15987,"project_id":6138686,"sha":"9bd08e99256614045cc9ef1f32a6a7b4fec56d50","ref":"pr-12294","status":"failed","source":"push","created_at":"2020-05-10T18:46:50.220Z","updated_at":"2020-05-10T19:28:54.279Z","web_url":"https://gitlab.com/coq/coq/-/pipelines/144552572"},"web_url":"https://gitlab.com/coq/coq/-/jobs/545885204","artifacts":[{"file_type":"trace","size":57757,"filename":"job.log","file_format":null}],"runner":{"id":380986,"description":"shared-runners-manager-5.gitlab.com","ip_address":"34.74.209.140","active":true,"paused":false,"is_shared":true,"runner_type":"instance_type","name":"gitlab-runner","online":false,"status":"stale"},"artifacts_expire_at":null,"tag_list":[]}
{"id":545885203,"status":"canceled","stage":"stage-1","name":"test-suite:edge+4.11+trunk+dune","ref":"pr-12294","tag":false,"coverage":null,"allow_failure":true,"created_at":"2020-05-10T18:46:50.402Z","started_at":"2020-05-10T18:46:53.448Z","finished_at":"2020-05-10T19:28:53.893Z","duration":2520.444979,"queued_duration":1.980974,"user":{"id":2256237,"username":"coqbot","name":"coqbot","state":"active","avatar_url":"https://gitlab.com/uploads/-/system/user/avatar/2256237/avatar.png","web_url":"https://gitlab.com/coqbot","created_at":"2018-04-28T07:53:57.210Z","bio":"Hello, I'm a bot.","location":"","public_email":"","skype":"","linkedin":"","twitter":"","website_url":"","organization":"","job_title":"","pronouns":null,"bot":false,"work_information":null,"followers":0,"following":0,"local_time":null},"commit":{"id":"9bd08e99256614045cc9ef1f32a6a7b4fec56d50","short_id":"9bd08e99","created_at":"2020-05-10T20:42:16.000+02:00","parent_ids":["f40839ee880ac3e79d560e26f55f462f8ffd2e05"],"title":"[errors] Don't raise inside exception printers","message":"[errors] Don't raise inside exception printers\n\nThis is wrong and not properly handled anymore, instead the handlers\nare expected to return the error message.\n\nThis is a partial backport of #11498 , as it turns out this doesn't\nmake sense in 8.11 neither.\n\nFixes #12291\n","author_name":"Emilio Jesus Gallego Arias","author_email":"e+git@x80.org","authored_date":"2020-05-10T20:42:16.000+02:00","committer_name":"Emilio Jesus Gallego Arias","committer_email":"e+git@x80.org","committed_date":"2020-05-10T20:42:16.000+02:00","trailers":{},"web_url":"https://gitlab.com/coq/coq/-/commit/9bd08e99256614045cc9ef1f32a6a7b4fec56d50"},"pipeline":{"id":144552572,"iid":15987,"project_id":6138686,"sha":"9bd08e99256614045cc9ef1f32a6a7b4fec56d50","ref":"pr-12294","status":"failed","source":"push","created_at":"2020-05-10T18:46:50.220Z","updated_at":"2020-05-10T19:28:54.279Z","web_url":"https://gitlab.com/coq/coq/-/pipelines/144552572"},"web_url":"https://gitlab.com/coq/coq/-/jobs/545885203","artifacts":[{"file_type":"trace","size":97782,"filename":"job.log","file_format":null}],"runner":{"id":44028,"description":"shared-runners-manager-3.gitlab.com","ip_address":"35.196.21.178","active":true,"paused":false,"is_shared":true,"runner_type":"instance_type","name":"gitlab-runner","online":false,"status":"stale"},"artifacts_expire_at":null,"tag_list":[]}
{"id":545885202,"status":"success","stage":"stage-1","name":"pkg:nix","ref":"pr-12294","tag":false,"coverage":null,"allow_failure":false,"created_at":"2020-05-10T18:46:50.389Z","started_at":"2020-05-10T18:46:53.408Z","finished_at":"2020-05-10T19:27:17.493Z","duration":2424.084793,"queued_duration":1.960137,"user":{"id":2256237,"username":"coqbot","name":"coqbot","state":"active","avatar_url":"https://gitlab.com/uploads/-/system/user/avatar/2256237/avatar.png","web_url":"https://gitlab.com/coqbot","created_at":"2018-04-28T07:53:57.210Z","bio":"Hello, I'm a bot.","location":"","public_email":"","skype":"","linkedin":"","twitter":"","website_url":"","organization":"","job_title":"","pronouns":null,"bot":false,"work_information":null,"followers":0,"following":0,"local_time":null},"commit":{"id":"9bd08e99256614045cc9ef1f32a6a7b4fec56d50","short_id":"9bd08e99","created_at":"2020-05-10T20:42:16.000+02:00","parent_ids":["f40839ee880ac3e79d560e26f55f462f8ffd2e05"],"title":"[errors] Don't raise inside exception printers","message":"[errors] Don't raise inside exception printers\n\nThis is wrong and not properly handled anymore, instead the handlers\nare expected to return the error message.\n\nThis is a partial backport of #11498 , as it turns out this doesn't\nmake sense in 8.11 neither.\n\nFixes #12291\n","author_name":"Emilio Jesus Gallego Arias","author_email":"e+git@x80.org","authored_date":"2020-05-10T20:42:16.000+02:00","committer_name":"Emilio Jesus Gallego Arias","committer_email":"e+git@x80.org","committed_date":"2020-05-10T20:42:16.000+02:00","trailers":{},"web_url":"https://gitlab.com/coq/coq/-/commit/9bd08e99256614045cc9ef1f32a6a7b4fec56d50"},"pipeline":{"id":144552572,"iid":15987,"project_id":6138686,"sha":"9bd08e99256614045cc9ef1f32a6a7b4fec56d50","ref":"pr-12294","status":"failed","source":"push","created_at":"2020-05-10T18:46:50.220Z","updated_at":"2020-05-10T19:28:54.279Z","web_url":"https://gitlab.com/coq/coq/-/pipelines/144552572"},"web_url":"https://gitlab.com/coq/coq/-/jobs/545885202","artifacts":[{"file_type":"trace","size":572864,"filename":"job.log","file_format":null}],"runner":{"id":380987,"description":"shared-runners-manager-6.gitlab.com","ip_address":"34.74.239.13","active":true,"paused":false,"is_shared":true,"runner_type":"instance_type","name":"gitlab-runner","online":false,"status":"stale"},"artifacts_expire_at":null,"tag_list":[]}
{"id":545885201,"status":"success","stage":"stage-1","name":"pkg:opam","ref":"pr-12294","tag":false,"coverage":null,"allow_failure":false,"created_at":"2020-05-10T18:46:50.375Z","started_at":"2020-05-10T18:46:53.313Z","finished_at":"2020-05-10T19:13:30.652Z","duration":1597.339595,"queued_duration":1.888626,"user":{"id":2256237,"username":"coqbot","name":"coqbot","state":"active","avatar_url":"https://gitlab.com/uploads/-/system/user/avatar/2256237/avatar.png","web_url":"https://gitlab.com/coqbot","created_at":"2018-04-28T07:53:57.210Z","bio":"Hello, I'm a bot.","location":"","public_email":"","skype":"","linkedin":"","twitter":"","website_url":"","organization":"","job_title":"","pronouns":null,"bot":false,"work_information":null,"followers":0,"following":0,"local_time":null},"commit":{"id":"9bd08e99256614045cc9ef1f32a6a7b4fec56d50","short_id":"9bd08e99","created_at":"2020-05-10T20:42:16.000+02:00","parent_ids":["f40839ee880ac3e79d560e26f55f462f8ffd2e05"],"title":"[errors] Don't raise inside exception printers","message":"[errors] Don't raise inside exception printers\n\nThis is wrong and not properly handled anymore, instead the handlers\nare expected to return the error message.\n\nThis is a partial backport of #11498 , as it turns out this doesn't\nmake sense in 8.11 neither.\n\nFixes #12291\n","author_name":"Emilio Jesus Gallego Arias","author_email":"e+git@x80.org","authored_date":"2020-05-10T20:42:16.000+02:00","committer_name":"Emilio Jesus Gallego Arias","committer_email":"e+git@x80.org","committed_date":"2020-05-10T20:42:16.000+02:00","trailers":{},"web_url":"https://gitlab.com/coq/coq/-/commit/9bd08e99256614045cc9ef1f32a6a7b4fec56d50"},"pipeline":{"id":144552572,"iid":15987,"project_id":6138686,"sha":"9bd08e99256614045cc9ef1f32a6a7b4fec56d50","ref":"pr-12294","status":"failed","source":"push","created_at":"2020-05-10T18:46:50.220Z","updated_at":"2020-05-10T19:28:54.279Z","web_url":"https://gitlab.com/coq/coq/-/pipelines/144552572"},"web_url":"https://gitlab.com/coq/coq/-/jobs/545885201","artifacts":[{"file_type":"trace","size":45661,"filename":"job.log","file_format":null}],"runner":null,"artifacts_expire_at":null,"tag_list":[]}
{"id":545885200,"status":"success","stage":"stage-1","name":"lint","ref":"pr-12294","tag":false,"coverage":null,"allow_failure":false,"created_at":"2020-05-10T18:46:50.362Z","started_at":"2020-05-10T18:46:53.274Z","finished_at":"2020-05-10T18:51:45.165Z","duration":291.890865,"queued_duration":1.869258,"user":{"id":2256237,"username":"coqbot","name":"coqbot","state":"active","avatar_url":"https://gitlab.com/uploads/-/system/user/avatar/2256237/avatar.png","web_url":"https://gitlab.com/coqbot","created_at":"2018-04-28T07:53:57.210Z","bio":"Hello, I'm a bot.","location":"","public_email":"","skype":"","linkedin":"","twitter":"","website_url":"","organization":"","job_title":"","pronouns":null,"bot":false,"work_information":null,"followers":0,"following":0,"local_time":null},"commit":{"id":"9bd08e99256614045cc9ef1f32a6a7b4fec56d50","short_id":"9bd08e99","created_at":"2020-05-10T20:42:16.000+02:00","parent_ids":["f40839ee880ac3e79d560e26f55f462f8ffd2e05"],"title":"[errors] Don't raise inside exception printers","message":"[errors] Don't raise inside exception printers\n\nThis is wrong and not properly handled anymore, instead the handlers\nare expected to return the error message.\n\nThis is a partial backport of #11498 , as it turns out this doesn't\nmake sense in 8.11 neither.\n\nFixes #12291\n","author_name":"Emilio Jesus Gallego Arias","author_email":"e+git@x80.org","authored_date":"2020-05-10T20:42:16.000+02:00","committer_name":"Emilio Jesus Gallego Arias","committer_email":"e+git@x80.org","committed_date":"2020-05-10T20:42:16.000+02:00","trailers":{},"web_url":"https://gitlab.com/coq/coq/-/commit/9bd08e99256614045cc9ef1f32a6a7b4fec56d50"},"pipeline":{"id":144552572,"iid":15987,"project_id":6138686,"sha":"9bd08e99256614045cc9ef1f32a6a7b4fec56d50","ref":"pr-12294","status":"failed","source":"push","created_at":"2020-05-10T18:46:50.220Z","updated_at":"2020-05-10T19:28:54.279Z","web_url":"https://gitlab.com/coq/coq/-/pipelines/144552572"},"web_url":"https://gitlab.com/coq/coq/-/jobs/545885200","artifacts":[{"file_type":"trace","size":36622,"filename":"job.log","file_format":null}],"runner":{"id":44949,"description":"shared-runners-manager-4.gitlab.com","ip_address":"13.37.237.197","active":true,"paused":false,"is_shared":true,"runner_type":"instance_type","name":"gitlab-runner","online":false,"status":"stale"},"artifacts_expire_at":null,"tag_list":[]}
{"id":545885199,"status":"canceled","stage":"stage-1","name":"windows32","ref":"pr-12294","tag":false,"coverage":null,"allow_failure":false,"created_at":"2020-05-10T18:46:50.336Z","started_at":"2020-05-10T18:46:51.690Z","finished_at":"2020-05-10T19:28:53.882Z","duration":2522.19185,"queued_duration":0.300523,"user":{"id":2256237,"username":"coqbot","name":"coqbot","state":"active","avatar_url":"https://gitlab.com/uploads/-/system/user/avatar/2256237/avatar.png","web_url":"https://gitlab.com/coqbot","created_at":"2018-04-28T07:53:57.210Z","bio":"Hello, I'm a bot.","location":"","public_email":"","skype":"","linkedin":"","twitter":"","website_url":"","organization":"","job_title":"","pronouns":null,"bot":false,"work_information":null,"followers":0,"following":0,"local_time":null},"commit":{"id":"9bd08e99256614045cc9ef1f32a6a7b4fec56d50","short_id":"9bd08e99","created_at":"2020-05-10T20:42:16.000+02:00","parent_ids":["f40839ee880ac3e79d560e26f55f462f8ffd2e05"],"title":"[errors] Don't raise inside exception printers","message":"[errors] Don't raise inside exception printers\n\nThis is wrong and not properly handled anymore, instead the handlers\nare expected to return the error message.\n\nThis is a partial backport of #11498 , as it turns out this doesn't\nmake sense in 8.11 neither.\n\nFixes #12291\n","author_name":"Emilio Jesus Gallego Arias","author_email":"e+git@x80.org","authored_date":"2020-05-10T20:42:16.000+02:00","committer_name":"Emilio Jesus Gallego Arias","committer_email":"e+git@x80.org","committed_date":"2020-05-10T20:42:16.000+02:00","trailers":{},"web_url":"https://gitlab.com/coq/coq/-/commit/9bd08e99256614045cc9ef1f32a6a7b4fec56d50"},"pipeline":{"id":144552572,"iid":15987,"project_id":6138686,"sha":"9bd08e99256614045cc9ef1f32a6a7b4fec56d50","ref":"pr-12294","status":"failed","source":"push","created_at":"2020-05-10T18:46:50.220Z","updated_at":"2020-05-10T19:28:54.279Z","web_url":"https://gitlab.com/coq/coq/-/pipelines/144552572"},"web_url":"https://gitlab.com/coq/coq/-/jobs/545885199","artifacts":[{"file_type":"trace","size":150418,"filename":"job.log","file_format":null}],"runner":null,"artifacts_expire_at":null,"tag_list":["windows-inria"]}
{"id":545885198,"status":"canceled","stage":"stage-1","name":"windows64","ref":"pr-12294","tag":false,"coverage":null,"allow_failure":false,"created_at":"2020-05-10T18:46:50.315Z","started_at":"2020-05-10T18:46:51.632Z","finished_at":"2020-05-10T19:28:53.869Z","duration":2522.237273,"queued_duration":0.257816,"user":{"id":2256237,"username":"coqbot","name":"coqbot","state":"active","avatar_url":"https://gitlab.com/uploads/-/system/user/avatar/2256237/avatar.png","web_url":"https://gitlab.com/coqbot","created_at":"2018-04-28T07:53:57.210Z","bio":"Hello, I'm a bot.","location":"","public_email":"","skype":"","linkedin":"","twitter":"","website_url":"","organization":"","job_title":"","pronouns":null,"bot":false,"work_information":null,"followers":0,"following":0,"local_time":null},"commit":{"id":"9bd08e99256614045cc9ef1f32a6a7b4fec56d50","short_id":"9bd08e99","created_at":"2020-05-10T20:42:16.000+02:00","parent_ids":["f40839ee880ac3e79d560e26f55f462f8ffd2e05"],"title":"[errors] Don't raise inside exception printers","message":"[errors] Don't raise inside exception printers\n\nThis is wrong and not properly handled anymore, instead the handlers\nare expected to return the error message.\n\nThis is a partial backport of #11498 , as it turns out this doesn't\nmake sense in 8.11 neither.\n\nFixes #12291\n","author_name":"Emilio Jesus Gallego Arias","author_email":"e+git@x80.org","authored_date":"2020-05-10T20:42:16.000+02:00","committer_name":"Emilio Jesus Gallego Arias","committer_email":"e+git@x80.org","committed_date":"2020-05-10T20:42:16.000+02:00","trailers":{},"web_url":"https://gitlab.com/coq/coq/-/commit/9bd08e99256614045cc9ef1f32a6a7b4fec56d50"},"pipeline":{"id":144552572,"iid":15987,"project_id":6138686,"sha":"9bd08e99256614045cc9ef1f32a6a7b4fec56d50","ref":"pr-12294","status":"failed","source":"push","created_at":"2020-05-10T18:46:50.220Z","updated_at":"2020-05-10T19:28:54.279Z","web_url":"https://gitlab.com/coq/coq/-/pipelines/144552572"},"web_url":"https://gitlab.com/coq/coq/-/jobs/545885198","artifacts":[{"file_type":"trace","size":152047,"filename":"job.log","file_format":null}],"runner":null,"artifacts_expire_at":null,"tag_list":["windows-inria"]}
{"id":545885197,"status":"success","stage":"stage-1","name":"build:quick","ref":"pr-12294","tag":false,"coverage":null,"allow_failure":true,"created_at":"2020-05-10T18:46:50.300Z","started_at":"2020-05-10T18:46:53.223Z","finished_at":"2020-05-10T18:57:56.824Z","duration":663.601508,"queued_duration":1.863039,"user":{"id":2256237,"username":"coqbot","name":"coqbot","state":"active","avatar_url":"https://gitlab.com/uploads/-/system/user/avatar/2256237/avatar.png","web_url":"https://gitlab.com/coqbot","created_at":"2018-04-28T07:53:57.210Z","bio":"Hello, I'm a bot.","location":"","public_email":"","skype":"","linkedin":"","twitter":"","website_url":"","organization":"","job_title":"","pronouns":null,"bot":false,"work_information":null,"followers":0,"following":0,"local_time":null},"commit":{"id":"9bd08e99256614045cc9ef1f32a6a7b4fec56d50","short_id":"9bd08e99","created_at":"2020-05-10T20:42:16.000+02:00","parent_ids":["f40839ee880ac3e79d560e26f55f462f8ffd2e05"],"title":"[errors] Don't raise inside exception printers","message":"[errors] Don't raise inside exception printers\n\nThis is wrong and not properly handled anymore, instead the handlers\nare expected to return the error message.\n\nThis is a partial backport of #11498 , as it turns out this doesn't\nmake sense in 8.11 neither.\n\nFixes #12291\n","author_name":"Emilio Jesus Gallego Arias","author_email":"e+git@x80.org","authored_date":"2020-05-10T20:42:16.000+02:00","committer_name":"Emilio Jesus Gallego Arias","committer_email":"e+git@x80.org","committed_date":"2020-05-10T20:42:16.000+02:00","trailers":{},"web_url":"https://gitlab.com/coq/coq/-/commit/9bd08e99256614045cc9ef1f32a6a7b4fec56d50"},"pipeline":{"id":144552572,"iid":15987,"project_id":6138686,"sha":"9bd08e99256614045cc9ef1f32a6a7b4fec56d50","ref":"pr-12294","status":"failed","source":"push","created_at":"2020-05-10T18:46:50.220Z","updated_at":"2020-05-10T19:28:54.279Z","web_url":"https://gitlab.com/coq/coq/-/pipelines/144552572"},"web_url":"https://gitlab.com/coq/coq/-/jobs/545885197","artifacts":[{"file_type":"trace","size":223757,"filename":"job.log","file_format":null}],"runner":null,"artifacts_expire_at":"2020-05-17T18:57:51.349Z","tag_list":[]}
{"id":545885196,"status":"canceled","stage":"stage-1","name":"build:base+async","ref":"pr-12294","tag":false,"coverage":null,"allow_failure":true,"created_at":"2020-05-10T18:46:50.286Z","started_at":"2020-05-10T18:46:52.938Z","finished_at":"2020-05-10T19:28:53.857Z","duration":2520.918882,"queued_duration":1.593852,"user":{"id":2256237,"username":"coqbot","name":"coqbot","state":"active","avatar_url":"https://gitlab.com/uploads/-/system/user/avatar/2256237/avatar.png","web_url":"https://gitlab.com/coqbot","created_at":"2018-04-28T07:53:57.210Z","bio":"Hello, I'm a bot.","location":"","public_email":"","skype":"","linkedin":"","twitter":"","website_url":"","organization":"","job_title":"","pronouns":null,"bot":false,"work_information":null,"followers":0,"following":0,"local_time":null},"commit":{"id":"9bd08e99256614045cc9ef1f32a6a7b4fec56d50","short_id":"9bd08e99","created_at":"2020-05-10T20:42:16.000+02:00","parent_ids":["f40839ee880ac3e79d560e26f55f462f8ffd2e05"],"title":"[errors] Don't raise inside exception printers","message":"[errors] Don't raise inside exception printers\n\nThis is wrong and not properly handled anymore, instead the handlers\nare expected to return the error message.\n\nThis is a partial backport of #11498 , as it turns out this doesn't\nmake sense in 8.11 neither.\n\nFixes #12291\n","author_name":"Emilio Jesus Gallego Arias","author_email":"e+git@x80.org","authored_date":"2020-05-10T20:42:16.000+02:00","committer_name":"Emilio Jesus Gallego Arias","committer_email":"e+git@x80.org","committed_date":"2020-05-10T20:42:16.000+02:00","trailers":{},"web_url":"https://gitlab.com/coq/coq/-/commit/9bd08e99256614045cc9ef1f32a6a7b4fec56d50"},"pipeline":{"id":144552572,"iid":15987,"project_id":6138686,"sha":"9bd08e99256614045cc9ef1f32a6a7b4fec56d50","ref":"pr-12294","status":"failed","source":"push","created_at":"2020-05-10T18:46:50.220Z","updated_at":"2020-05-10T19:28:54.279Z","web_url":"https://gitlab.com/coq/coq/-/pipelines/144552572"},"web_url":"https://gitlab.com/coq/coq/-/jobs/545885196","artifacts":[{"file_type":"trace","size":282947,"filename":"job.log","file_format":null}],"runner":null,"artifacts_expire_at":null,"tag_list":[]}
{"id":545885195,"status":"success","stage":"stage-1","name":"build:edge+flambda:dune:dev","ref":"pr-12294","tag":false,"coverage":null,"allow_failure":false,"created_at":"2020-05-10T18:46:50.275Z","started_at":"2020-05-10T18:46:52.470Z","finished_at":"2020-05-10T18:55:03.038Z","duration":490.568549,"queued_duration":1.143378,"user":{"id":2256237,"username":"coqbot","name":"coqbot","state":"active","avatar_url":"https://gitlab.com/uploads/-/system/user/avatar/2256237/avatar.png","web_url":"https://gitlab.com/coqbot","created_at":"2018-04-28T07:53:57.210Z","bio":"Hello, I'm a bot.","location":"","public_email":"","skype":"","linkedin":"","twitter":"","website_url":"","organization":"","job_title":"","pronouns":null,"bot":false,"work_information":null,"followers":0,"following":0,"local_time":null},"commit":{"id":"9bd08e99256614045cc9ef1f32a6a7b4fec56d50","short_id":"9bd08e99","created_at":"2020-05-10T20:42:16.000+02:00","parent_ids":["f40839ee880ac3e79d560e26f55f462f8ffd2e05"],"title":"[errors] Don't raise inside exception printers","message":"[errors] Don't raise inside exception printers\n\nThis is wrong and not properly handled anymore, instead the handlers\nare expected to return the error message.\n\nThis is a partial backport of #11498 , as it turns out this doesn't\nmake sense in 8.11 neither.\n\nFixes #12291\n","author_name":"Emilio Jesus Gallego Arias","author_email":"e+git@x80.org","authored_date":"2020-05-10T20:42:16.000+02:00","committer_name":"Emilio Jesus Gallego Arias","committer_email":"e+git@x80.org","committed_date":"2020-05-10T20:42:16.000+02:00","trailers":{},"web_url":"https://gitlab.com/coq/coq/-/commit/9bd08e99256614045cc9ef1f32a6a7b4fec56d50"},"pipeline":{"id":144552572,"iid":15987,"project_id":6138686,"sha":"9bd08e99256614045cc9ef1f32a6a7b4fec56d50","ref":"pr-12294","status":"failed","source":"push","created_at":"2020-05-10T18:46:50.220Z","updated_at":"2020-05-10T19:28:54.279Z","web_url":"https://gitlab.com/coq/coq/-/pipelines/144552572"},"web_url":"https://gitlab.com/coq/coq/-/jobs/545885195","artifacts":[{"file_type":"trace","size":46489,"filename":"job.log","file_format":null}],"runner":null,"artifacts_expire_at":"2020-05-17T18:54:58.386Z","tag_list":[]}
{"id":545885194,"status":"success","stage":"stage-1","name":"build:edge+flambda","ref":"pr-12294","tag":false,"coverage":null,"allow_failure":false,"created_at":"2020-05-10T18:46:50.262Z","started_at":"2020-05-10T18:46:52.093Z","finished_at":"2020-05-10T19:05:38.917Z","duration":1126.824134,"queued_duration":0.782793,"user":{"id":2256237,"username":"coqbot","name":"coqbot","state":"active","avatar_url":"https://gitlab.com/uploads/-/system/user/avatar/2256237/avatar.png","web_url":"https://gitlab.com/coqbot","created_at":"2018-04-28T07:53:57.210Z","bio":"Hello, I'm a bot.","location":"","public_email":"","skype":"","linkedin":"","twitter":"","website_url":"","organization":"","job_title":"","pronouns":null,"bot":false,"work_information":null,"followers":0,"following":0,"local_time":null},"commit":{"id":"9bd08e99256614045cc9ef1f32a6a7b4fec56d50","short_id":"9bd08e99","created_at":"2020-05-10T20:42:16.000+02:00","parent_ids":["f40839ee880ac3e79d560e26f55f462f8ffd2e05"],"title":"[errors] Don't raise inside exception printers","message":"[errors] Don't raise inside exception printers\n\nThis is wrong and not properly handled anymore, instead the handlers\nare expected to return the error message.\n\nThis is a partial backport of #11498 , as it turns out this doesn't\nmake sense in 8.11 neither.\n\nFixes #12291\n","author_name":"Emilio Jesus Gallego Arias","author_email":"e+git@x80.org","authored_date":"2020-05-10T20:42:16.000+02:00","committer_name":"Emilio Jesus Gallego Arias","committer_email":"e+git@x80.org","committed_date":"2020-05-10T20:42:16.000+02:00","trailers":{},"web_url":"https://gitlab.com/coq/coq/-/commit/9bd08e99256614045cc9ef1f32a6a7b4fec56d50"},"pipeline":{"id":144552572,"iid":15987,"project_id":6138686,"sha":"9bd08e99256614045cc9ef1f32a6a7b4fec56d50","ref":"pr-12294","status":"failed","source":"push","created_at":"2020-05-10T18:46:50.220Z","updated_at":"2020-05-10T19:28:54.279Z","web_url":"https://gitlab.com/coq/coq/-/pipelines/144552572"},"web_url":"https://gitlab.com/coq/coq/-/jobs/545885194","artifacts":[{"file_type":"trace","size":305363,"filename":"job.log","file_format":null}],"runner":null,"artifacts_expire_at":"2020-05-17T19:05:36.380Z","tag_list":[]}
{"id":545885193,"status":"success","stage":"stage-1","name":"build:base+32bit","ref":"pr-12294","tag":false,"coverage":null,"allow_failure":false,"created_at":"2020-05-10T18:46:50.249Z","started_at":"2020-05-10T18:46:51.733Z","finished_at":"2020-05-10T18:58:23.604Z","duration":691.870324,"queued_duration":0.438467,"user":{"id":2256237,"username":"coqbot","name":"coqbot","state":"active","avatar_url":"https://gitlab.com/uploads/-/system/user/avatar/2256237/avatar.png","web_url":"https://gitlab.com/coqbot","created_at":"2018-04-28T07:53:57.210Z","bio":"Hello, I'm a bot.","location":"","public_email":"","skype":"","linkedin":"","twitter":"","website_url":"","organization":"","job_title":"","pronouns":null,"bot":false,"work_information":null,"followers":0,"following":0,"local_time":null},"commit":{"id":"9bd08e99256614045cc9ef1f32a6a7b4fec56d50","short_id":"9bd08e99","created_at":"2020-05-10T20:42:16.000+02:00","parent_ids":["f40839ee880ac3e79d560e26f55f462f8ffd2e05"],"title":"[errors] Don't raise inside exception printers","message":"[errors] Don't raise inside exception printers\n\nThis is wrong and not properly handled anymore, instead the handlers\nare expected to return the error message.\n\nThis is a partial backport of #11498 , as it turns out this doesn't\nmake sense in 8.11 neither.\n\nFixes #12291\n","author_name":"Emilio Jesus Gallego Arias","author_email":"e+git@x80.org","authored_date":"2020-05-10T20:42:16.000+02:00","committer_name":"Emilio Jesus Gallego Arias","committer_email":"e+git@x80.org","committed_date":"2020-05-10T20:42:16.000+02:00","trailers":{},"web_url":"https://gitlab.com/coq/coq/-/commit/9bd08e99256614045cc9ef1f32a6a7b4fec56d50"},"pipeline":{"id":144552572,"iid":15987,"project_id":6138686,"sha":"9bd08e99256614045cc9ef1f32a6a7b4fec56d50","ref":"pr-12294","status":"failed","source":"push","created_at":"2020-05-10T18:46:50.220Z","updated_at":"2020-05-10T19:28:54.279Z","web_url":"https://gitlab.com/coq/coq/-/pipelines/144552572"},"web_url":"https://gitlab.com/coq/coq/-/jobs/545885193","artifacts":[{"file_type":"trace","size":296657,"filename":"job.log","file_format":null}],"runner":null,"artifacts_expire_at":"2020-05-17T18:57:55.660Z","tag_list":[]}
{"id":545885192,"status":"success","stage":"stage-1","name":"build:base","ref":"pr-12294","tag":false,"coverage":null,"allow_failure":false,"created_at":"2020-05-10T18:46:50.236Z","started_at":"2020-05-10T18:46:51.690Z","finished_at":"2020-05-10T18:56:16.087Z","duration":564.396817,"queued_duration":0.409513,"user":{"id":2256237,"username":"coqbot","name":"coqbot","state":"active","avatar_url":"https://gitlab.com/uploads/-/system/user/avatar/2256237/avatar.png","web_url":"https://gitlab.com/coqbot","created_at":"2018-04-28T07:53:57.210Z","bio":"Hello, I'm a bot.","location":"","public_email":"","skype":"","linkedin":"","twitter":"","website_url":"","organization":"","job_title":"","pronouns":null,"bot":false,"work_information":null,"followers":0,"following":0,"local_time":null},"commit":{"id":"9bd08e99256614045cc9ef1f32a6a7b4fec56d50","short_id":"9bd08e99","created_at":"2020-05-10T20:42:16.000+02:00","parent_ids":["f40839ee880ac3e79d560e26f55f462f8ffd2e05"],"title":"[errors] Don't raise inside exception printers","message":"[errors] Don't raise inside exception printers\n\nThis is wrong and not properly handled anymore, instead the handlers\nare expected to return the error message.\n\nThis is a partial backport of #11498 , as it turns out this doesn't\nmake sense in 8.11 neither.\n\nFixes #12291\n","author_name":"Emilio Jesus Gallego Arias","author_email":"e+git@x80.org","authored_date":"2020-05-10T20:42:16.000+02:00","committer_name":"Emilio Jesus Gallego Arias","committer_email":"e+git@x80.org","committed_date":"2020-05-10T20:42:16.000+02:00","trailers":{},"web_url":"https://gitlab.com/coq/coq/-/commit/9bd08e99256614045cc9ef1f32a6a7b4fec56d50"},"pipeline":{"id":144552572,"iid":15987,"project_id":6138686,"sha":"9bd08e99256614045cc9ef1f32a6a7b4fec56d50","ref":"pr-12294","status":"failed","source":"push","created_at":"2020-05-10T18:46:50.220Z","updated_at":"2020-05-10T19:28:54.279Z","web_url":"https://gitlab.com/coq/coq/-/pipelines/144552572"},"web_url":"https://gitlab.com/coq/coq/-/jobs/545885192","artifacts":[{"file_type":"trace","size":321078,"filename":"job.log","file_format":null}],"runner":null,"artifacts_expire_at":"2020-05-17T18:56:13.711Z","tag_list":[]}
