[{"url":"https://api.github.com/repos/coq/coq/issues/comments/337520029","html_url":"https://github.com/coq/coq/issues/3366#issuecomment-337520029","issue_url":"https://api.github.com/repos/coq/coq/issues/3366","id":337520029,"node_id":"MDEyOklzc3VlQ29tbWVudDMzNzUyMDAyOQ==","user":{"login":"coqbot","id":13040781,"node_id":"MDQ6VXNlcjEzMDQwNzgx","avatar_url":"https://avatars.githubusercontent.com/u/13040781?v=4","gravatar_id":"","url":"https://api.github.com/users/coqbot","html_url":"https://github.com/coqbot","followers_url":"https://api.github.com/users/coqbot/followers","following_url":"https://api.github.com/users/coqbot/following{/other_user}","gists_url":"https://api.github.com/users/coqbot/gists{/gist_id}","starred_url":"https://api.github.com/users/coqbot/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/coqbot/subscriptions","organizations_url":"https://api.github.com/users/coqbot/orgs","repos_url":"https://api.github.com/users/coqbot/repos","events_url":"https://api.github.com/users/coqbot/events{/privacy}","received_events_url":"https://api.github.com/users/coqbot/received_events","type":"User","site_admin":false},"created_at":"2014-06-08T21:47:02Z","updated_at":"2017-10-18T09:19:46Z","author_association":"CONTRIBUTOR","body":"Comment author: @JasonGross\n\nModule X.\n  Set Universe Polymorphism.\n  Inductive paths A (x : A) : forall _ : A, Type := idpath : paths A x x.\n  Notation \"x = y\" := (@ paths _ x y) (at level 70, no associativity) : type_scope.\n\n  Axioms A B : Type.\n  Axiom P : A = B.\n  Definition foo : A = B.\n    abstract (rewrite <- P; reflexivity).\n  (* Error: internal_paths_rew already exists. *)\n  Defined. (* Anomaly: Uncaught exception Not_found(_). Please report. *)\n\n\nIf I use [Fail Defined], I get \"This command has not failed!\"\n\n","reactions":{"url":"https://api.github.com/repos/coq/coq/issues/comments/337520029/reactions","total_count":0,"+1":0,"-1":0,"laugh":0,"hooray":0,"confused":0,"heart":0,"rocket":0,"eyes":0},"performed_via_github_app":null},{"url":"https://api.github.com/repos/coq/coq/issues/comments/337520030","html_url":"https://github.com/coq/coq/issues/3366#issuecomment-337520030","issue_url":"https://api.github.com/repos/coq/coq/issues/3366","id":337520030,"node_id":"MDEyOklzc3VlQ29tbWVudDMzNzUyMDAzMA==","user":{"login":"coqbot","id":13040781,"node_id":"MDQ6VXNlcjEzMDQwNzgx","avatar_url":"https://avatars.githubusercontent.com/u/13040781?v=4","gravatar_id":"","url":"https://api.github.com/users/coqbot","html_url":"https://github.com/coqbot","followers_url":"https://api.github.com/users/coqbot/followers","following_url":"https://api.github.com/users/coqbot/following{/other_user}","gists_url":"https://api.github.com/users/coqbot/gists{/gist_id}","starred_url":"https://api.github.com/users/coqbot/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/coqbot/subscriptions","organizations_url":"https://api.github.com/users/coqbot/orgs","repos_url":"https://api.github.com/users/coqbot/repos","events_url":"https://api.github.com/users/coqbot/events{/privacy}","received_events_url":"https://api.github.com/users/coqbot/received_events","type":"User","site_admin":false},"created_at":"2015-02-25T14:28:58Z","updated_at":"2017-10-18T09:19:46Z","author_association":"CONTRIBUTOR","body":"Comment author: @maximedenes\n\nDo you know which commit fixed the underlying anomaly? I could then test the capture of the anomaly independently.\n\n","reactions":{"url":"https://api.github.com/repos/coq/coq/issues/comments/337520030/reactions","total_count":0,"+1":0,"-1":0,"laugh":0,"hooray":0,"confused":0,"heart":0,"rocket":0,"eyes":0},"performed_via_github_app":null},{"url":"https://api.github.com/repos/coq/coq/issues/comments/337520032","html_url":"https://github.com/coq/coq/issues/3366#issuecomment-337520032","issue_url":"https://api.github.com/repos/coq/coq/issues/3366","id":337520032,"node_id":"MDEyOklzc3VlQ29tbWVudDMzNzUyMDAzMg==","user":{"login":"coqbot","id":13040781,"node_id":"MDQ6VXNlcjEzMDQwNzgx","avatar_url":"https://avatars.githubusercontent.com/u/13040781?v=4","gravatar_id":"","url":"https://api.github.com/users/coqbot","html_url":"https://github.com/coqbot","followers_url":"https://api.github.com/users/coqbot/followers","following_url":"https://api.github.com/users/coqbot/following{/other_user}","gists_url":"https://api.github.com/users/coqbot/gists{/gist_id}","starred_url":"https://api.github.com/users/coqbot/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/coqbot/subscriptions","organizations_url":"https://api.github.com/users/coqbot/orgs","repos_url":"https://api.github.com/users/coqbot/repos","events_url":"https://api.github.com/users/coqbot/events{/privacy}","received_events_url":"https://api.github.com/users/coqbot/received_events","type":"User","site_admin":false},"created_at":"2015-02-26T04:47:51Z","updated_at":"2017-10-18T09:19:47Z","author_association":"CONTRIBUTOR","body":"Comment author: @JasonGross\n\nPerhaps bug [BZ#3684](https://github.com/coq/coq/issues?q=is%3Aissue%20%22Original%20bug%20ID%3A%20BZ%233684%22) is a better one to use:\n\nDefinition foo : Set.\n  refine ($(abstract admit)$).\n(* Toplevel input, characters 15-42:\nAnomaly: Uncaught exception Not_found(_). Please report. *)\n\nPMP said: \"Should be morally fixed in trunk. See the comments of commit 9295b3db to understand that the reality is not that bright, but at least, typical use-case should go through just fine.\"\n\nAlternatively, bug [BZ#3392](https://github.com/coq/coq/issues?q=is%3Aissue%20%22Original%20bug%20ID%3A%20BZ%233392%22) has another anomaly on [Defined], which I bisected.\n\n","reactions":{"url":"https://api.github.com/repos/coq/coq/issues/comments/337520032/reactions","total_count":0,"+1":0,"-1":0,"laugh":0,"hooray":0,"confused":0,"heart":0,"rocket":0,"eyes":0},"performed_via_github_app":null},{"url":"https://api.github.com/repos/coq/coq/issues/comments/337520034","html_url":"https://github.com/coq/coq/issues/3366#issuecomment-337520034","issue_url":"https://api.github.com/repos/coq/coq/issues/3366","id":337520034,"node_id":"MDEyOklzc3VlQ29tbWVudDMzNzUyMDAzNA==","user":{"login":"coqbot","id":13040781,"node_id":"MDQ6VXNlcjEzMDQwNzgx","avatar_url":"https://avatars.githubusercontent.com/u/13040781?v=4","gravatar_id":"","url":"https://api.github.com/users/coqbot","html_url":"https://github.com/coqbot","followers_url":"https://api.github.com/users/coqbot/followers","following_url":"https://api.github.com/users/coqbot/following{/other_user}","gists_url":"https://api.github.com/users/coqbot/gists{/gist_id}","starred_url":"https://api.github.com/users/coqbot/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/coqbot/subscriptions","organizations_url":"https://api.github.com/users/coqbot/orgs","repos_url":"https://api.github.com/users/coqbot/repos","events_url":"https://api.github.com/users/coqbot/events{/privacy}","received_events_url":"https://api.github.com/users/coqbot/received_events","type":"User","site_admin":false},"created_at":"2015-02-26T09:33:39Z","updated_at":"2017-10-18T09:19:47Z","author_association":"CONTRIBUTOR","body":"Comment author: @gares\n\nI guess it was the fix to 3392.  In any case now Defined works, and Fail Defined \"works\" too.  So the test case is bogus.\n\nIf you want an anomaly\n\n  BackTo 999999.\n\nBut then Fail does not mask it... so I guess this bug is also fixed.\n\n","reactions":{"url":"https://api.github.com/repos/coq/coq/issues/comments/337520034/reactions","total_count":0,"+1":0,"-1":0,"laugh":0,"hooray":0,"confused":0,"heart":0,"rocket":0,"eyes":0},"performed_via_github_app":null},{"url":"https://api.github.com/repos/coq/coq/issues/comments/337520036","html_url":"https://github.com/coq/coq/issues/3366#issuecomment-337520036","issue_url":"https://api.github.com/repos/coq/coq/issues/3366","id":337520036,"node_id":"MDEyOklzc3VlQ29tbWVudDMzNzUyMDAzNg==","user":{"login":"coqbot","id":13040781,"node_id":"MDQ6VXNlcjEzMDQwNzgx","avatar_url":"https://avatars.githubusercontent.com/u/13040781?v=4","gravatar_id":"","url":"https://api.github.com/users/coqbot","html_url":"https://github.com/coqbot","followers_url":"https://api.github.com/users/coqbot/followers","following_url":"https://api.github.com/users/coqbot/following{/other_user}","gists_url":"https://api.github.com/users/coqbot/gists{/gist_id}","starred_url":"https://api.github.com/users/coqbot/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/coqbot/subscriptions","organizations_url":"https://api.github.com/users/coqbot/orgs","repos_url":"https://api.github.com/users/coqbot/repos","events_url":"https://api.github.com/users/coqbot/events{/privacy}","received_events_url":"https://api.github.com/users/coqbot/received_events","type":"User","site_admin":false},"created_at":"2015-02-26T23:52:31Z","updated_at":"2017-10-18T09:19:47Z","author_association":"CONTRIBUTOR","body":"Comment author: @maximedenes\n\nAlright, so it seems we can't reproduce it. Feel free to reopen the bug if you have a new repro case.\n\n","reactions":{"url":"https://api.github.com/repos/coq/coq/issues/comments/337520036/reactions","total_count":0,"+1":0,"-1":0,"laugh":0,"hooray":0,"confused":0,"heart":0,"rocket":0,"eyes":0},"performed_via_github_app":null}]