[{"url":"https://api.github.com/repos/coq/coq/issues/comments/337525117","html_url":"https://github.com/coq/coq/issues/3680#issuecomment-337525117","issue_url":"https://api.github.com/repos/coq/coq/issues/3680","id":337525117,"node_id":"MDEyOklzc3VlQ29tbWVudDMzNzUyNTExNw==","user":{"login":"coqbot","id":13040781,"node_id":"MDQ6VXNlcjEzMDQwNzgx","avatar_url":"https://avatars.githubusercontent.com/u/13040781?v=4","gravatar_id":"","url":"https://api.github.com/users/coqbot","html_url":"https://github.com/coqbot","followers_url":"https://api.github.com/users/coqbot/followers","following_url":"https://api.github.com/users/coqbot/following{/other_user}","gists_url":"https://api.github.com/users/coqbot/gists{/gist_id}","starred_url":"https://api.github.com/users/coqbot/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/coqbot/subscriptions","organizations_url":"https://api.github.com/users/coqbot/orgs","repos_url":"https://api.github.com/users/coqbot/repos","events_url":"https://api.github.com/users/coqbot/events{/privacy}","received_events_url":"https://api.github.com/users/coqbot/received_events","type":"User","site_admin":false},"created_at":"2014-09-29T21:56:54Z","updated_at":"2017-10-18T09:34:29Z","author_association":"CONTRIBUTOR","body":"Comment author: @JasonGross\n\nThe message \"Error: Conversion test raised an anomaly\", e.g., on some [refine]s, is mostly useless.  It should mention which anomaly was raised.\n\n","reactions":{"url":"https://api.github.com/repos/coq/coq/issues/comments/337525117/reactions","total_count":0,"+1":0,"-1":0,"laugh":0,"hooray":0,"confused":0,"heart":0,"rocket":0,"eyes":0},"performed_via_github_app":null},{"url":"https://api.github.com/repos/coq/coq/issues/comments/337525119","html_url":"https://github.com/coq/coq/issues/3680#issuecomment-337525119","issue_url":"https://api.github.com/repos/coq/coq/issues/3680","id":337525119,"node_id":"MDEyOklzc3VlQ29tbWVudDMzNzUyNTExOQ==","user":{"login":"coqbot","id":13040781,"node_id":"MDQ6VXNlcjEzMDQwNzgx","avatar_url":"https://avatars.githubusercontent.com/u/13040781?v=4","gravatar_id":"","url":"https://api.github.com/users/coqbot","html_url":"https://github.com/coqbot","followers_url":"https://api.github.com/users/coqbot/followers","following_url":"https://api.github.com/users/coqbot/following{/other_user}","gists_url":"https://api.github.com/users/coqbot/gists{/gist_id}","starred_url":"https://api.github.com/users/coqbot/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/coqbot/subscriptions","organizations_url":"https://api.github.com/users/coqbot/orgs","repos_url":"https://api.github.com/users/coqbot/repos","events_url":"https://api.github.com/users/coqbot/events{/privacy}","received_events_url":"https://api.github.com/users/coqbot/received_events","type":"User","site_admin":false},"created_at":"2015-02-27T19:59:45Z","updated_at":"2017-10-18T09:34:29Z","author_association":"CONTRIBUTOR","body":"Comment author: @ppedrot\n\nI don't think so. It should not mention any anomaly at all, because this error should not appear. The true problem is that we should not feed ill-typed terms to functions from the kernel.\n\n","reactions":{"url":"https://api.github.com/repos/coq/coq/issues/comments/337525119/reactions","total_count":0,"+1":0,"-1":0,"laugh":0,"hooray":0,"confused":0,"heart":0,"rocket":0,"eyes":0},"performed_via_github_app":null}]